source/usage-examples/command.txt, source/usage-examples/distinct.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker/ExampleHeader/usage-examples/overview
Not all usage examples contain an "Example" header above the actual code example. Added this to the examples that lacked it, since the majority contain it.
=> Standardized example header in usage examples

source/fundamentals/crud/read-operations/text.txt, source/usage-examples/bulkWrite.txt, source/usage-examples/command.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt
Stage:
------
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/Typos-And-Cleanup-Branch/
Changes:
-----------
* removed "Overview" header from all usage examples, they are inconsistently in some of the usage examples and not in others. That header should not be there at all
* Fixed typo in `source/fundamentals/crud/read-operations/text.txt`
=> Typos and cleanup branch

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/geo.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/code-snippets/indexes/unique.js, source/fundamentals.txt, source/fundamentals/indexes.txt, source/tutorials.txt
Obviously, I'll squash my commits into something less ugly when we're done 😺 
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker/DOCSP-8055-index-tutorial/fundamentals/indexes
Jira: https://jira.mongodb.org/browse/DOCSP-8055
=> DOCSP-8055 adds page about indexes

source/api-documentation.txt, source/code-snippets/usage-examples/bulkWrite-example.js, source/code-snippets/usage-examples/command.js, source/code-snippets/usage-examples/count.js, source/code-snippets/usage-examples/deleteMany.js, source/code-snippets/usage-examples/deleteOne.js, source/code-snippets/usage-examples/distinct.js, source/code-snippets/usage-examples/find.js, source/code-snippets/usage-examples/findOne.js, source/code-snippets/usage-examples/insertMany.js, source/code-snippets/usage-examples/insertOne.js, source/code-snippets/usage-examples/replaceOne.js, source/code-snippets/usage-examples/updateMany.js, source/code-snippets/usage-examples/updateOne.js, source/index.txt, source/usage-examples/changeStream.txt
- added note linking users to the connection guide above the usage example snippet
- updated ``fullDocument`` field documentation to match the definition found [here](https://docs.mongodb.com/manual/reference/method/db.collection.watch/) (subtle differences in interpretation -- this definition matches my own testing)
- limited usage of monospace font to specific coding terms
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/ce3554b/node/docsworker/standardization/usage-examples/changeStream
=> standardizing change stream example with other usage exs

source/index.txt
No JIRA
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/9c1217d/node/docsworker-xlarge/index-typo-fix-022820/
=> fix link to collations on index page

.prettierrc, source/code-snippets/usage-examples/replaceOne.js
Our current configuration enforces trailing commas on multi-line constructions. I would suggest that we continue to enforce trailing commas on objects, but omit them from function calls. See my second commit for an example of how trailing commas on function calls can have slightly baffling results.
=> Trailing comma setting adjustment

source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-9539
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/06ff5de/node/docsworker-xlarge/DOCSP-9539-fix-delete-one-many/usage-examples/deleteOne
and
https://docs-mongodbcom-staging.corp.mongodb.com/06ff5de/node/docsworker-xlarge/DOCSP-9539-fix-delete-one-many/usage-examples/deleteMany
=> DOCSP-9539: remove mention of errmsg from delete operations

source/usage-examples/findOne.txt
Grammar fix.
find -> finds
JIRA:
None
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/21393e5/node/docsworker-xlarge/040820-typo-fix/usage-examples/findOne
=> fix typo in findOne usage example

source/fundamentals/crud/read-operations/project.txt
JIRA: 
https://jira.mongodb.org/browse/DOCSP-10100
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/bcbcf7d/node/docsworker/DOCSP-10100-projection/fundamentals/crud/read-operations/project
- Removed mention of insert statement.
- Provided additional example and mentioned order in projection doesn't change the order in which they are returned.
- Added link to additional projection documentation in the manual at the end because there have been comments about drawing the user away from the documentation by providing links too early.
=> DOCSP-10100: PR based on feedback for projections

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/limit.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10102
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/968780f/node/docsworker/DOCSP-10102-feedback-limit-results/fundamentals/crud/read-operations/limit
I did not include the following feedback items since this is a document on limit, and perhaps would belong in the page on sort instead:
- In the second sort, it now includes an `author`, without any explanation of why. (omitted the second sort instead as it was not necessary)
- For the sort example with `length`, it might be worth mentioning how the results are sorted when multiple lengths are the same.
=> DOCSP-10102: address feedback on limit results

source/code-snippets/crud/arrayFilters.js, source/fundamentals/crud/write-operations.txt, source/fundamentals/crud/write-operations/embedded-arrays.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10259
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/8156d45/node/docsworker/DOCSP-10259-feedback-update-arrays/fundamentals/crud/write-operations/embedded-arrays
Addressed the following:
-updated order of articles in ToC
-added first-position and all-position operators as well as an additional example of filtered-position
-added link to other available array update operators
=> DOCSP-10259: address feedback on update arrays

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-11514
Staging:
Start from: https://docs-mongodbcom-staging.corp.mongodb.com/ea1509f/node/docsworker-xlarge/DOCSP-11514-add-links-read-write/fundamentals/crud
Click Read and Write Operation links.
=> DOCSP-11514: add links to read and write operation non-landing pages

source/fundamentals/connection.txt, source/includes/atlas-search.rst, source/quick-start.txt, source/usage-examples.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-11555
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/42514a6/node/docsworker-xlarge/DOCSP-11555-fix-atlas-link/quick-start
https://docs-mongodborg-staging.corp.mongodb.com/42514a6/node/docsworker-xlarge/DOCSP-11555-fix-atlas-link/fundamentals/connection
https://docs-mongodborg-staging.corp.mongodb.com/42514a6/node/docsworker-xlarge/DOCSP-11555-fix-atlas-link/usage-examples
https://docs-mongodborg-staging.corp.mongodb.com/42514a6/node/docsworker-xlarge/DOCSP-11555-fix-atlas-link/fundamentals/crud/read-operations/text
Caused by change to rstspec.toml `:atlas:` directive
=> DOCSP-11555: fix link to atlas in quickstart

source/fundamentals.txt, source/usage-examples/delete-operations.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-11718
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/aebf623/node/docsworker-xlarge/DOCSP-11718-add-toc/fundamentals
Checked all other non-landing drawer pages and they all contained an in-document ToC. Users must be opening new tabs/windows using the nav links to arrive at these pages.
=> DOCSP-11718: add ToC to fundamentals non-landing page

source/code-snippets/indexes/text.js
`TypeError: movies.find(...).projection is not a function`
Discovered when exploring docs (**$textSearch**): via [doc example](https://docs.mongodb.com/drivers/node/fundamentals/crud/read-operations/text)
Hopefully, this helps avoid some confusion for those learning :)
=> bug: code-snippet invalid function call (ie typo)

source/fundamentals/crud/query-document.txt
no JIRA
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/4ecea5a/node/docsworker-xlarge/011421-node-fix/fundamentals/crud/query-document
=> fix syntax of examples on query-document

.github/pull_request_template.md, source/fundamentals/crud/write-operations/insert.txt, source/usage-examples/changeStream.txt
This splits the iterative and event-based paradigms more clearly and
adds a warning not to mix the two. It also includes a missing `async`
statement that was reported via feedback in Slack.
https://jira.mongodb.org/browse/DOCSP-13986
https://docs-mongodbcom-staging.corp.mongodb.com/8a9b10c/node/docsworker-xlarge/DOCSP-13986/usage-examples/changeStream
=> task: clarify change stream paradigms

source/faq.txt, source/fundamentals/connection.txt
The `connectTimeoutMS` default value is 10000 milliseconds, and we had it listed as 30000 millis.
https://jira.mongodb.org/browse/DOCSP-13986
https://docs-mongodbcom-staging.corp.mongodb.com/a8fb166/node/docsworker-xlarge/DOCSP-13986/fundamentals/connection#connection-options
https://docs-mongodbcom-staging.corp.mongodb.com/a8fb166/node/docsworker-xlarge/DOCSP-13986/faq
=> bug: update connectTimeoutMS default value

source/code-snippets/crud/cursor.js, source/fundamentals/crud/read-operations/cursor.txt
Per the ticket description in mongodb@4, `stream()` must now be called on the cursor to use the stream API.
https://jira.mongodb.org/browse/DOCSP-14071
https://docs-mongodbcom-staging.corp.mongodb.com/faaae47/node/docsworker-xlarge/DOCSP-14071/fundamentals/crud/read-operations/cursor/#stream-api
=> DOCSP-14071: use stream() on cursor for streaming api

source/fundamentals/connection.txt
This documents the `directConnection` parameter in the options list and explains it in the context of replica sets.
Target is all branches so I will cherry-pick this to v3.6 and push.
https://jira.mongodb.org/browse/DOCSP-14304
https://docs-mongodbcom-staging.corp.mongodb.com/d40be7e/node/docsworker-xlarge/DOCSP-14304/fundamentals/connection/#connect-to-a-replica-set
=> DOCSP-14304: document directConnection

source/fundamentals/authentication/enterprise-mechanisms.txt
Update Node 4.0 Authentication Parameters to specify that `gssapiServiceName` is deprecated. 
https://jira.mongodb.org/browse/DOCSP-14337
https://docs-mongodbcom-staging.corp.mongodb.com/a43f746/node/docsworker-xlarge/DOSCP-14337/fundamentals/authentication/enterprise-mechanisms/
=> Doscp 14337

source/fundamentals/crud/read-operations/limit.txt
https://jira.mongodb.org/browse/DOCSP-15136
https://docs-mongodbcom-staging.corp.mongodb.com/87c8d69/node/docsworker-xlarge/DOCSP-15136-fix-limit/fundamentals/crud/read-operations/limit/
=> DOCSP-15136: fix text in fundamentals limit page

source/index.txt
This PR removes the note from the master branch that these docs are for the 3.6 version of the driver and where to find docs for older versions.
N/A
https://docs-mongodbcom-staging.corp.mongodb.com/212f2bd/node/docsworker-xlarge/remove-note/
=> remove note from upcoming/master about driver version

source/fundamentals/crud/read-operations/limit.txt
* DOCSP-15136: fix text in fundamentals limit page
(cherry picked from commit 231dbf96d1640a5eea63908bfc00efc9d6509d29)
https://jira.mongodb.org/browse/DOCSP-15136
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/node/docsworker-xlarge/NNNNNNNNNNN/
=> DOCSP-15136: fix text in fundamentals limit page (#152)

source/quick-start.txt
https://jira.mongodb.org/browse/DOCSP-15299
https://docs-mongodbcom-staging.corp.mongodb.com/1c479b3/node/docsworker-xlarge/DOCSP-15299-atlas-sample-data-link/quick-start/
=> DOCSP-15299: add a link to Atlas Sample Data guide

source/quick-start.txt
* DOCSP-15299: add a link to Atlas Sample Data guide
(cherry picked from commit 0f80a7850bb34085818e8c1458dd7f1849e46e1c)
https://jira.mongodb.org/browse/DOCSP-15299
https://docs-mongodbcom-staging.corp.mongodb.com/7c1fbd4/node/docsworker-xlarge/v3.6/quick-start/
=> DOCSP-15299: add a link to Atlas Sample Data guide (#159)

source/includes/language-compatibility-table-node.rst, source/includes/mongodb-compatibility-table-node.rst
https://jira.mongodb.org/browse/DOCSP-15475
https://docs-mongodbcom-staging.corp.mongodb.com/181f084/node/docsworker-xlarge/DOCSP-15475-ColumnNames/compatibility/
=> DOCSP-15475 updated table header name

source/fundamentals/connection.txt
https://jira.mongodb.org/browse/DOCSP-12263
https://docs-mongodbcom-staging.corp.mongodb.com/b56fb45/node/docsworker-xlarge/DOCSP-12263-KeepAliveDefault/fundamentals/connection/
=> DOCSP-12263 default time for KeepAliveInitialDelay

source/usage-examples/find.txt, source/usage-examples/findOne.txt
Clarified the intro of both Usage Examples > Find Operation pages.
https://jira.mongodb.org/browse/DOCSP-16097
https://docs-mongodbcom-staging.corp.mongodb.com/7cb12b0/node/docsworker-xlarge/DOCSP-16097-ClarifyQueryOps/usage-examples/findOne/
https://docs-mongodbcom-staging.corp.mongodb.com/7cb12b0/node/docsworker-xlarge/DOCSP-16097-ClarifyQueryOps/usage-examples/find/
=> DOCSP-16097 Clarifying Intro

source/faq.txt
Added a note that you cannot use maxTimeMS for MongoClientSettings.
https://jira.mongodb.org/browse/DOCSP-14237
https://docs-mongodbcom-staging.corp.mongodb.com/73de378/node/docsworker-xlarge/DOCS-14237-maxTimeMSNote/faq/#what-is-the-difference-between--connecttimeoutms----sockettimeoutms--and--maxtimems--
=> DOCS-14237 max time ms note

source/fundamentals/crud/write-operations/insert.txt
Differences from v3.6 page:
- Return object of each insert operation object
- InsertOneResult does not have insertedCount
- API directive
https://jira.mongodb.org/browse/DOCSP-16443
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-16443-InsertImprovement/fundamentals/crud/write-operations/insert/
=> DOCSP-16443 insert improvement

snooty.toml, source/fundamentals.txt, source/fundamentals/crud/write-operations/insert.txt, source/includes/fundamentals-sections.rst, source/index.txt
https://jira.mongodb.org/browse/DOCSP-14696
Fundamentals Landing Page: https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-14696-fundamentals-description/fundamentals/
Index Page:
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-14696-fundamentals-description/
=> DOCSP-14696: Create Fundamentals Landing Page with Content

source/code-snippets/usage-examples/updateOne.js, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
https://jira.mongodb.org/browse/DOCSP-17299
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17299-node-usage-grammar-fix/usage-examples/updateOne/
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17299-node-usage-grammar-fix/usage-examples/updateMany/
=> DOSCP-17299 node usage grammar fix

source/fundamentals/crud/write-operations/change-a-document.txt
Add information about using aggregation pipelines in update operations and test that aggregation pipelines in update operations work in MongoDB node Driver Version 3.6 and 4.0.
I went through the [aggregation pipelines in update operations tutorial](https://docs.mongodb.com/manual/tutorial/update-documents-with-aggregation-pipeline/) using v3.6 and v4.0 of the node driver and did not experience issues. 
https://jira.mongodb.org/browse/DOCSP-15085
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-15085-Link-To-Aggregations-In-Updates/fundamentals/crud/write-operations/change-a-document/#update
=> Docsp 15085 aggregations in updates

source/fundamentals/crud/query-document.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/read-operations/project.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/read-operations/skip.txt, source/fundamentals/crud/read-operations/sort.txt, source/fundamentals/crud/read-operations/text.txt, source/includes/access-cursor-note.rst
https://jira.mongodb.org/browse/DOCSP-17340
Cursor Fundamentals page:
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17340-cursor-updates/fundamentals/crud/read-operations/cursor/
Page containing new note: 
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17340-cursor-updates/fundamentals/crud/read-operations/retrieve/
=> DOCSP-17340 cursor updates

source/fundamentals/crud/query-document.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/read-operations/project.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/read-operations/skip.txt, source/fundamentals/crud/read-operations/sort.txt, source/fundamentals/crud/read-operations/text.txt, source/includes/access-cursor-note.rst
* DOCSP-17340: updates and additions to make access to cursor information easier
* DOCSP-17340: updates and additions to make access to cursor information easier
* DOCSP-17340: added cursor access note to more pages
(cherry picked from commit cd15596ee5a17cf6c414c444d726b0ec69d057d3)
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/node/docsworker-xlarge/NNNNNNNNNNN/
=> DOCSP-17340 cursor updates (#200)

source/includes/changestream-paradigm-warning.rst, source/usage-examples/changeStream.txt
This changes the warning text to state that mixing paradigms will error. [Upstream PR](https://github.com/mongodb/node-mongodb-native/pull/2871)
https://jira.mongodb.org/browse/DOCSP-17414
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17414/usage-examples/changeStream/
=> DOCSP-17414: ChangeStream paradim errors

source/includes/localhost-connection.rst
Changes the localhost note to use port 27017 instead of 27107.
:fire: This is only on the v3.6 branch, not the master branch.
https://jira.mongodb.org/browse/DOCS-14637
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCS-14637/quick-start/#connect-to-localhost
=> correct port transposition error

source/fundamentals/crud/query-document.txt
Correctly describes the `$lt` operator.
https://jira.mongodb.org/browse/DOCSP-17505
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17505/fundamentals/crud/query-document/#comparison-operators
=> DOCSP-17505: correct $lt description

source/index.txt
Fixed error I made with the API documentation version when cherry-picking.
https://jira.mongodb.org/browse/DOCSP-17643 
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/APIDocumentaionVersion/
=> fixed api documentation version

source/usage-examples.txt
Listed all available usage examples on the page for the reader to easily find.
I followed the format of how the Java builders page lists the pages within it's section: https://docs.mongodb.com/drivers/java/sync/current/fundamentals/builders/#available-builders
https://jira.mongodb.org/browse/DOCSP-17406
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17406-ListingUsageExamples/usage-examples/#available-usage-examples
=> DOCSP-17406 listing available usage examples

source/whats-new.txt
Fixed:
- a broken link a user reported 
- a broken link I found
- a trailing / in the 3.6 section
https://jira.mongodb.org/browse/DOCSP-17885
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17885-brokenLinks/whats-new/#authentication
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17885-brokenLinks/whats-new/#unified-topology
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17885-brokenLinks/whats-new/#what-s-new-in-3.6
=> DOCSP-17885 broken links

snooty.toml, source/fundamentals/versioned-api.txt
This corrects the link for the ServerApi interface on the versioned API page.
https://jira.mongodb.org/browse/DOCSP-17971
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17971/fundamentals/versioned-api/
=> Fix link to Node ServerApi interface

source/fundamentals/connection.txt, source/includes/localhost-connection.rst, source/quick-start.txt, source/whats-new.txt
https://jira.mongodb.org/browse/DOCSP-17791
[Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17791-new-local-instructions/quick-start/)
[Connection Guide](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17791-new-local-instructions/fundamentals/connection/)
[Build Log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=611172827dcf012930215135)
=> DOCSP-17791: update instructions on connecting to locally hosted server

source/code-snippets/usage-examples/findOne.js
Sort does not sort on a valid field. Needs to sort on "imdb.rating" rather than "rating".  "rating" is not a valid field in the sample dataset.
NA
https://docs-mongodbcom-staging.corp.mongodb.com/8b555f3/node/docsworker-xlarge/Fix-Find-One-Incorrect-Sort/usage-examples/findOne/
=> need to sort on imdb.rating rather than rating

source/fundamentals/logging.txt
Fixed the command monitoring link and added cluster monitoring 
https://jira.mongodb.org/browse/DOCSP-17837
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17837-linkFix/fundamentals/logging/
=> DOCSP-17837 link fix

source/code-snippets/usage-examples/deleteOne.js, source/usage-examples/deleteOne.txt
https://jira.mongodb.org/browse/DOCSP-18066
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18066-deleteone-fix/usage-examples/deleteOne/
=> DOCSP-18066: fixed example for DeleteOne

snooty.toml, source/faq.txt, source/fundamentals/aggregation.txt, source/fundamentals/collations.txt, source/fundamentals/connection.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/gridfs.txt, source/fundamentals/logging.txt, source/fundamentals/promises.txt, source/fundamentals/versioned-api.txt, source/index.txt, source/usage-examples/bulkWrite.txt, source/usage-examples/changeStream.txt, source/usage-examples/command.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
Replaced API directive with a constant.
Note: There is no 3.7 link for `serverapiversion` and `serverapi` on the Versioned API page. I confirmed with an engineer that it's ok to link to 4.0 since it's the same logic.
https://jira.mongodb.org/browse/DOCSP-18482
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=613005017dcf012930cee60f
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18482-APIConstants/
=> DOCSP-18482 api constants

snooty.toml, source/faq.txt, source/fundamentals/aggregation.txt, source/fundamentals/collations.txt, source/fundamentals/connection.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/gridfs.txt, source/fundamentals/promises.txt, source/fundamentals/typescript.txt, source/fundamentals/versioned-api.txt, source/index.txt, source/usage-examples/bulkWrite.txt, source/usage-examples/changeStream.txt, source/usage-examples/command.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt, source/whats-new.txt
This PR changes the API links to use source constants and camelCases them.
`rg -o '\{\+api\+\}\w.*\.html(#\w+)?' .` returns no results (checks for `{+api}+/<lowercase letter followed by standard link format>`
Manual checking of every changed link also ensured anchor targets are correct. Even though modules/classes/interfaces begin with a capital letter and are camel-cased, options are camel-cased but beginning with a lowercase letter
https://jira.mongodb.org/browse/DOCSP-18513
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=613780be7dcf01293077b2ac
https://docs-mongodborg-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18513/
=> Docsp 18513

snooty.toml
Fix constant name which was incorrectly handled in merge. I accidentally [overwrote Nathan's renaming of this constant in this PR](https://github.com/mongodb/docs-node/commit/3e6321a823bbd146e899b2cac5e0ad037ce006d6)
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=613a783ec608bec57fe78dd0
https://docs-mongodborg-staging.corp.mongodb.com/node/docsworker-xlarge/fix-incorrect-merge/
=> fix constant name

source/code-snippets/usage-examples/changeStream.js, source/usage-examples/changeStream.txt
Updated the watch for changes usage example to be more natural -- I spoke to Daria and she provided me a snippet to replace the current one with.
This will be cherry-picked across all the pages since its the same page for all.
https://jira.mongodb.org/browse/DOCSP-18158
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61410b4dc608bec57ff3c51a
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18158-WatchUsageExampleUpdate/usage-examples/changeStream/
=> DOCSP-18158 updated change stream example

source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection.txt
https://jira.mongodb.org/browse/DOCSP-18838
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=614e84a8bc80a0834ba3a0c9
[Direct Connection](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18838-broken-link-fix/fundamentals/connection/#direct-connection)
[SCRAM SHA-256](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18838-broken-link-fix/fundamentals/authentication/mechanisms/#scram-sha-256)
=> DOCSP-18838: fix broken links

snooty.toml, source/compatibility.txt
This adds information about compatibility tables to the page. It uses shareable content so that the content can be used across all driver sites.
https://jira.mongodb.org/browse/DOCSP-19453
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6189c9c4c13055282d2e5cc8
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-19453/compatibility/#mongodb-compatibility-table
=> About compat tables

snooty.toml, source/index.txt
- Fixed version constant
- Added constants from master
- Updated the API link to use new constant
https://jira.mongodb.org/browse/DOCSP-19330
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61d75d7f41accb36337011e7
Snooty build logs aren't working at the moment
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-19330/
=> (DOCSP-19330) Update source constants in Node v3.6 branch

source/index.txt
* (DOCSP-20494) standardize driver intros: node.js
https://jira.mongodb.org/browse/DOCSP-20533
**Paste your workerpool job link here**
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/node/docsworker-xlarge/NNNNNNNNNNN/
=> (DOCSP-20494) standardize driver intros: node.js (#278)

source/fundamentals.txt, source/fundamentals/utf8-validation.txt, source/includes/fundamentals-sections.rst, source/whats-new.txt
https://jira.mongodb.org/browse/DOCSP-20056
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61f2c8ddbcf82347e58d0b02
[What's New link](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-20056-utf8-option/whats-new/#what-s-new-in-4.3)
[ToC](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-20056-utf8-option/fundamentals/)
[UTF-8 Validation Page](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-20056-utf8-option/fundamentals/utf8-validation/)
=> DOCSP-20056: UTF-8 validation options

source/fundamentals/stable-api.txt
None
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61f82c9f382d7fe4ee4cdd00
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/013121-fix-versioned-to-stable/fundamentals/stable-api/
=> Replace instance of versioned with stable

source/fundamentals.txt, source/fundamentals/csfle.txt, source/includes/fundamentals-sections.rst
I noticed that
- :doc:`Create and Query Time Series Collection </fundamentals/time-series>`
- :doc:`Specify Type Parameters with TypeScript </fundamentals/typescript>`
must've been accidentally backported to 3.7. Those pages don't exist on this branch, so I removed the toc items.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=621006f49c4c7f6bfb9c3e09
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18745-backport-v3.7/
=> Backport DOCSP-18745, remove deadend toc items

source/fundamentals.txt, source/fundamentals/csfle.txt, source/includes/fundamentals-sections.rst
I noticed that
:doc:Create and Query Time Series Collection </fundamentals/time-series>
:doc:Specify Type Parameters with TypeScript </fundamentals/typescript>
must've been accidentally backported to 3.7. Those pages don't exist on this branch, so I removed the toc items.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=621009329c4c7f6bfb9cf076
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18745-backport-v3.6/
=> merge DOCSP-18475, remove dead end toc items

source/index.txt
N/A
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6228fd731a622fb27492ad2f
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/add-ref/)
=> add ref to landing page for guides

source/fundamentals/gridfs.txt
Applies to all docs versions after 4.0
https://jira.mongodb.org/browse/DOCSP-21400
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6230a0820ab54725f1552f95
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-21400-remove-roles/fundamentals/gridfs/
=> DOCSP-21400: remove shared role references

source/usage-examples/changeStream.txt
Updated the watch usage example intro to show the API links early on opposed to the very end of the section.
https://jira.mongodb.org/browse/DOCSP-21009
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=623cdf700ab54725f1ec0ffc
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-21009-WatchUsageExample/usage-examples/changeStream/
=> DOCSP-21009 watch usage example

source/includes/fundamentals-sections.rst, source/quick-reference.txt
https://jira.mongodb.org/browse/DOCSP-21920
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62543aa10fdfea9c372d4680
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-21920-fix-api-links/quick-reference/
=> DOCSP-21920: fix api links on quick reference page

snooty.toml, source/whats-new.txt
Updated the link to the serverless deployment page.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=625888a40fdfea9c3713e601
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-22039-LinkFix/whats-new/#what-s-new-in-4.1
=> DOCSP-22039 link fix

source/quick-reference.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/050222-default-visible-output/quick-reference/
=> Hide output in io-code-block by default

source/code-snippets/monitoring/apm-subscribe.js, source/fundamentals/monitoring/command-monitoring.txt
Updated the example on the Cluster Monitoring page to include the monitorCommands option and a note calling out you must specify the option to enable monitoring.
JIRA - <https://jira.mongodb.org/browse/DOCSP-22799>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-22799/fundamentals/monitoring/command-monitoring/#event-subscription-example>
=> DOCSP-22799 updated example

source/quick-start.txt
Fixes mistake in quick-start code introduced in recent updates. Adds the "await client.connect()" line back. Applies to v4.6 and earlier.
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/070722-revert-quickstart-line/quick-start/
=> 070722 revert quickstart line

source/fundamentals/connection/network-compression.txt
Fixes a few references to zlib where it should be zstd.
=> docs: fix zstd/zlib references in docs

source/fundamentals/crud/read-operations/distinct.txt, source/usage-examples/distinct.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-23699>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-23699-fix-heading-format/>
=> DOCSP-23699: fixed format of a heading

source/fundamentals/encrypt-fields.txt
Updated :v6: links on encrypt page to use :ref:s
JIRA - https://jira.mongodb.org/browse/DOCSP-24285
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-24285/fundamentals/encrypt-fields/
=> DOCSP-24285 Updating QE/CSFLE links to refs

source/fundamentals/encrypt-fields.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/080222-typo-fix/fundamentals/encrypt-fields/#client-side-field-level-encryption--csfle-
=> fix typo on encrypt fields page

source/fundamentals/encrypt-fields.txt
(cherry picked from commit 46040820f4cea965c87a680d391f780f47b142ee)
Backport of https://github.com/mongodb/docs-node/pull/379
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.7/fundamentals/encrypt-fields/#queryable-encryption
=> fix typo on encrypt fields page (#379)

source/fundamentals/collations.txt, source/fundamentals/crud/query-document.txt, source/fundamentals/logging.txt, source/quick-start.txt
No JIRA ticket
This PR fixes the code-block rST indentation which silently failed to apply syntax highlighting for the specified language. While it's beyond expectations to review each file, to verify the syntax highlighting is applied, you'll need to individually inspect each code block with Chrome Tools for the "javascript" (or other) style in the code component:
Staging:
[Quick start](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/110922-fix-code-block-indentation/quick-start/)
[Collations](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/110922-fix-code-block-indentation/fundamentals/collations/)
[Specify a …
=> Fix code block indentation

source/fundamentals/typescript.txt, source/includes/limitations/limits.rst, source/whats-new.txt
**Notes**
- Original ticket mentions broad support for recursive schema types, but the original Node PR only reflects changes for mutually recursive schema types
- Changes to be made were discussed in this [Slack thread](https://mongodb.slack.com/archives/C0275HANT8E/p1669835552153679?thread_ts=1669758869.139549&cid=C0275HANT8E) due to incorrectly documented behavior/examples in the Node release notes.
**JIRA** 
<https://jira.mongodb.org/browse/DOCSP-25723>
**Staging** 
- [TypeScript page (Mutual Recursion Limitations)](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-25723-v4.11-mutually-recursive-schema-types/fundamentals/typescript/#mutual-recursion)
- [What's New in …
=> DOCSP-25723 Updates to Mutually Recursive Schema Types

source/fundamentals/typescript.txt, source/includes/limitations/limits.rst
Backporting information from https://github.com/mongodb/docs-node/pull/459 that is relevant to v4.10 and earlier
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.10/fundamentals/typescript/
=> Selective Backport DOCSP-25723

source/fundamentals/typescript.txt, source/includes/limitations/4.3.rst
(cherry picked from commit a3486025213c05644a140f6f47b01479c7d5df76)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.3/fundamentals/typescript/#mutual-recursion
=> Selective Backport DOCSP-25723 (#461)

source/fundamentals/crud/write-operations/change-a-document.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27238
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-27238-typo-fix/fundamentals/crud/write-operations/change-a-document/
**In addition to the typo fix I made some changes for clarity and changed the examples to be less confusing**
=> DOCSP-27238: typo fix & other cleanup

source/quick-reference.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-27405>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-27405-fix-quick-reference/quick-reference/
=> DOCSP-27405: fix insertOne method in the quick reference

source/fundamentals/promises.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27263
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-27263-remove-helpers/fundamentals/promises/
=> DOCSP-27263: remove references to deprecated helper methods

source/fundamentals/typescript.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27376
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-27376-dot-notation-unsupported/fundamentals/typescript/#type-safety-and-dot-notation
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-27376-dot-notation-unsupported/whats-new/#what-s-new-in-5.0
=> DOCSP-27376: removed support for dot notation in find*

source/code-snippets/usage-examples/changeStream.js, source/code-snippets/usage-examples/changeStream_listener.js, source/usage-examples/changeStream.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26099
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-26099-cs-iterable/usage-examples/changeStream/
=> DOCSP-26099: cs is an async iterable

source/code-snippets/usage-examples/changeStream.js, source/code-snippets/usage-examples/changeStream_listener.js, source/usage-examples/changeStream.txt
- [DOCSP-26099: cs is an async iterable (#498)](https://github.com/mongodb/docs-node/pull/498)
=> [v5.0] DOCSP-26099: cs is an async iterable (#498)

source/code-snippets/usage-examples/changeStream.js, source/code-snippets/usage-examples/changeStream_listener.js, source/usage-examples/changeStream.txt
- [DOCSP-26099: cs is an async iterable (#498)](https://github.com/mongodb/docs-node/pull/498)
=> [v4.14] DOCSP-26099: cs is an async iterable (#498)

source/code-snippets/usage-examples/changeStream.js, source/code-snippets/usage-examples/changeStream_listener.js, source/usage-examples/changeStream.txt
- [DOCSP-26099: cs is an async iterable (#498)](https://github.com/mongodb/docs-node/pull/498)
=> [v4.13] DOCSP-26099: cs is an async iterable (#498)

source/code-snippets/usage-examples/changeStream.js, source/code-snippets/usage-examples/changeStream_listener.js, source/usage-examples/changeStream.txt
- [DOCSP-26099: cs is an async iterable (#498)](https://github.com/mongodb/docs-node/pull/498)
=> [v4.12] DOCSP-26099: cs is an async iterable (#498)

source/faq.txt, source/fundamentals/connection/connection-options.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27863
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-27863-connectTimeoutMS-correct-default/fundamentals/connection/connection-options/
=> DOCSP-27863: correct default of connectTimeoutMS

source/faq.txt, source/fundamentals/connection/connection-options.txt
=> [v5.0] DOCSP-27863: correct default of connectTimeoutMS (#518)

source/faq.txt, source/fundamentals/connection/connection-options.txt
=> [v4.14] DOCSP-27863: correct default of connectTimeoutMS (#518)

source/faq.txt, source/fundamentals/connection/connection-options.txt
=> [v4.13] DOCSP-27863: correct default of connectTimeoutMS (#518)

source/faq.txt, source/fundamentals/connection/connection-options.txt
=> [v4.12] DOCSP-27863: correct default of connectTimeoutMS (#518)

source/faq.txt, source/fundamentals/connection/connection-options.txt
=> [v4.11] DOCSP-27863: correct default of connectTimeoutMS (#518)

source/faq.txt, source/fundamentals/connection/connection-options.txt
=> [v4.8] DOCSP-27863: correct default of connectTimeoutMS (#518)

source/faq.txt, source/fundamentals/connection/connection-options.txt
=> [v4.7] DOCSP-27863: correct default of connectTimeoutMS (#518)

source/faq.txt, source/fundamentals/connection/connection-options.txt
=> [v4.6] DOCSP-27863: correct default of connectTimeoutMS (#518)

source/faq.txt, source/fundamentals/connection/connection-options.txt
=> [v4.5] DOCSP-27863: correct default of connectTimeoutMS (#518)

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
=> [v5.0] Docsp 27849 connection monitoring (#531)

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
=> [v4.14] Docsp 27849 connection monitoring (#531)

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
=> [v4.13] Docsp 27849 connection monitoring (#531)

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
=> [v4.12] Docsp 27849 connection monitoring (#531)

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
=> [v4.11] Docsp 27849 connection monitoring (#531)

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
=> [v4.8] Docsp 27849 connection monitoring (#531)

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
=> [v4.7] Docsp 27849 connection monitoring (#531)

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
=> [v4.6] Docsp 27849 connection monitoring (#531)

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
=> [v4.5] Docsp 27849 connection monitoring (#531)

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
=> [v4.4] Docsp 27849 connection monitoring (#531)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v5.0] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.14] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.13] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.12] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.11] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.8] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.7] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.6] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.5] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.4] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.3] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
=> [v4.2] DOCSP-14352: fix multikey index description & example (#542)

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
This will backport the following commits from `master` to `v4.1`:
=> [v4.1] DOCSP-14352: fix multikey index description & example (#542)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.14] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.13] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.12] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.11] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.10] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.9] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.8] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.7] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.6] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.2] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
This will backport the following commits from `master` to `v4.1`:
=> [v4.1] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
This will backport the following commits from `master` to `v4.0`:
=> [v4.0] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.5] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.4] docsp-28100 - connection monitoring link (#556)

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
=> [v4.3] docsp-28100 - connection monitoring link (#556)

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
=> [v4.11] docsp-12262 - remove OCSP (#573)

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
=> [v4.10] docsp-12262 - remove OCSP (#573)

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
=> [v4.9] docsp-12262 - remove OCSP (#573)

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
=> [v4.8] docsp-12262 - remove OCSP (#573)

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
=> [v4.7] docsp-12262 - remove OCSP (#573)

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
=> [v4.6] docsp-12262 - remove OCSP (#573)

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
=> [v4.5] docsp-12262 - remove OCSP (#573)

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
=> [v4.4] docsp-12262 - remove OCSP (#573)

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
=> [v4.3] docsp-12262 - remove OCSP (#573)

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
=> [v4.2] docsp-12262 - remove OCSP (#573)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
This will backport the following commits from `master` to `v5.1`:
=> [v5.1] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v5.0] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.14] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.13] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.12] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.11] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.10] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.9] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.8] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.7] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.5] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.4] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.3] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
=> [v4.2] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
This will backport the following commits from `master` to `v4.1`:
=> [v4.1] add stableapi connection example (#590)

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
This will backport the following commits from `master` to `v4.0`:
=> [v4.0] add stableapi connection example (#590)

source/usage-examples/count.txt
This will backport the following commits from `master` to `v5.1`:
=> [v5.1] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v5.0] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.14] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.13] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.12] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.11] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.10] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.9] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.8] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.7] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.6] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.5] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.4] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.3] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
=> [v4.2] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
This will backport the following commits from `master` to `v4.1`:
=> [v4.1] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
This will backport the following commits from `master` to `v4.0`:
=> [v4.0] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
This will backport the following commits from `master` to `v3.7`:
=> [v3.7] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/usage-examples/count.txt
This will backport the following commits from `master` to `v3.6`:
=> [v3.6] DOCSP-27257 Add tip to avoid collScan on countDocuments (#611)

source/code-snippets/authentication/x509.js, source/fundamentals/authentication/mechanisms.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-18653
[**Staging**](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18653-x509-no-user/fundamentals/authentication/mechanisms/#x.509)
=> DOCSP-18653: remove username from x509 example

source/fundamentals/typescript.txt
The original wording of the section made it seem like the driver converts the _id field based on the given schema. This PR clarifies what the section was intended to convey.
JIRA - https://jira.mongodb.org/browse/DOCSP-28958
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-28958-typescript-find-and-id/fundamentals/typescript/#find-methods-and-the-_id-field
=> DOCSP-28958 Clarify Typescript Find and the _id section

source/fundamentals/typescript.txt
This will backport the following commits from `master` to `v5.2`:
=> [v5.2] DOCSP-28958 Clarify Typescript Find and the _id section (#644)

source/fundamentals/typescript.txt
This will backport the following commits from `master` to `v5.1`:
=> [v5.1] DOCSP-28958 Clarify Typescript Find and the _id section (#644)

source/fundamentals/typescript.txt
=> [v5.0] DOCSP-28958 Clarify Typescript Find and the _id section (#644)

source/fundamentals/typescript.txt
=> [v4.14] DOCSP-28958 Clarify Typescript Find and the _id section (#644)

source/fundamentals/typescript.txt
=> [v4.13] DOCSP-28958 Clarify Typescript Find and the _id section (#644)

source/fundamentals/typescript.txt
=> [v4.12] DOCSP-28958 Clarify Typescript Find and the _id section (#644)

source/fundamentals/typescript.txt
=> [v4.11] DOCSP-28958 Clarify Typescript Find and the _id section (#644)

source/fundamentals/typescript.txt
=> [v4.10] DOCSP-28958 Clarify Typescript Find and the _id section (#644)

source/fundamentals/typescript.txt
=> [v4.9] DOCSP-28958 Clarify Typescript Find and the _id section (#644)

source/fundamentals/typescript.txt
=> [v4.4] DOCSP-28958 Clarify Typescript Find and the _id section (#644)

source/faq.txt
JIRA - [DOCSP-26065](https://jira.mongodb.org/browse/DOCSP-26065)
Staging - [FAQ](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-26065-sockettimeout-behavior/faq/#what-happens-to-my-operations-if-my-client-disconnects-)
=> DOCSP-26065: socketTimeoutMS behavior

source/faq.txt, source/fundamentals/connection/connect.txt, source/fundamentals/transactions.txt, source/issues-and-help.txt, source/upgrade.txt
JIRA - [DOCSP-28558](https://jira.mongodb.org/browse/DOCSP-28558)
Staging - [FAQ](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-28558-client-faq/faq/#how-does-connection-pooling-work-in-the-node-driver-) | [Connection Guide](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-28558-client-faq/fundamentals/connection/connect/#atlas-connection-example)
=> DOCSP-28558: connection pool faq + reuse client tip

source/code-snippets/usage-examples/bulkWrite.js, source/usage-examples/bulkWrite.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29035
**[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-29035-remove-bw-properties/usage-examples/bulkWrite/)**
- [n/a] Did you run a grammar-check?
- [n/a] Are all the links working?
=> DOCSP-29035: remove deprecated accessors bulkWrite

source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/geo.txt, source/fundamentals/crud/read-operations/retrieve.txt
Ran the alas_but_one.py script in this repo.
=> typo fixes surfaced by script

config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-29563>
Staging - None
New redirects output from mut-redirects:
> Redirect 301 /docs/drivers/node/v3.6/fundamentals/csfle https://www.mongodb.com/docs/drivers/node/v3.6/fundamentals/encrypt-fields/
> Redirect 301 /docs/drivers/node/v3.7/fundamentals/csfle https://www.mongodb.com/docs/drivers/node/v3.7/fundamentals/encrypt-fields/
> Redirect 301 /docs/drivers/node/v4.0/fundamentals/csfle https://www.mongodb.com/docs/drivers/node/v4.0/fundamentals/encrypt-fields/
> Redirect 301 /docs/drivers/node/v4.1/fundamentals/csfle https://www.mongodb.com/docs/drivers/node/v4.1/fundamentals/encrypt-fields/
> Redirect 301 /docs/drivers/node/v4.2/fundamentals/csfle …
=> DOCSP-29563: redirect CSFLE to Encrypt Fields for all versions

source/fundamentals/connection.txt, source/fundamentals/connection/tls.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25770
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-25770-tls-setup/fundamentals/connection/tls/)
=> DOCSP-25770: TLS setup

source/code-snippets/crud/cursor.js, source/code-snippets/crud/startrek.js, source/code-snippets/crud/theaters.js, source/code-snippets/quick-reference.js, source/code-snippets/usage-examples/find.js, source/code-snippets/usage-examples/find.ts, source/fundamentals/crud/query-document.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/distinct.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/read-operations/project.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/read-operations/skip.txt, source/fundamentals/crud/read-operations/sort.txt, source/fundamentals/gridfs.txt, source/quick-reference.txt, source/usage-examples/find.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29345
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-29345-remove-foreach/
=> DOCSP-29345 - Replace forEach

source/index.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29626
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-29626-move-WN/#what-s-new and see left nav
=> DOCSP-29626: move what's new in nav

config/redirects
adding a redirect for versions below v4.3 because utf validation was introduced in v4.3
```
Redirect 301 /docs/drivers/node/v3.6/fundamentals/utf8-validation https://www.mongodb.com/docs/drivers/node/v3.6/
Redirect 301 /docs/drivers/node/v3.7/fundamentals/utf8-validation https://www.mongodb.com/docs/drivers/node/v3.7/
Redirect 301 /docs/drivers/node/v4.0/fundamentals/utf8-validation https://www.mongodb.com/docs/drivers/node/v4.0/
Redirect 301 /docs/drivers/node/v4.1/fundamentals/utf8-validation https://www.mongodb.com/docs/drivers/node/v4.1/
Redirect 301 /docs/drivers/node/v4.2/fundamentals/utf8-validation https://www.mongodb.com/docs/drivers/node/v4.2/
```
=> add redirect bc utf pg doesnt exist below v4.3

config/redirects, snooty.toml, source/fundamentals.txt, source/fundamentals/bson.txt, source/fundamentals/bson/undefined-values.txt, source/fundamentals/bson/utf8-validation.txt, source/fundamentals/crud/write-operations/upsert.txt, source/includes/fundamentals-sections.rst
merge conflicts in redirects and utf validation page.
=> backport #674 to v4.15

snooty.toml, source/fundamentals.txt, source/fundamentals/bson.txt, source/fundamentals/bson/undefined-values.txt, source/fundamentals/crud/write-operations/upsert.txt, source/includes/fundamentals-sections.rst
removed UTF validation page since feature doesnt exist for v4.2 and below. adjusted pages to reflect this
[fundamentals landing pg](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.2/fundamentals/)
[bson landing pg](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.2/fundamentals/bson/)
[undefined vals pg](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.2/fundamentals/bson/undefined-values/)
=> undefined values page & reorganization (backport #674 to v4.2)

source/fundamentals/crud/read-operations/retrieve.txt
JIRA - [DOCSP-29805](https://jira.mongodb.org/browse/DOCSP-29805)
[**Staging**](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-29805-find-no-query/fundamentals/crud/read-operations/retrieve/#find)
=> DOCSP-29805: no query criteria in find

source/code-snippets/indexes/text.js, source/fundamentals/crud/read-operations/text.txt, source/fundamentals/indexes.txt
JIRA - [DOCSP-29802](https://jira.mongodb.org/browse/DOCSP-29802)
Staging:
- [Indexes page](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-29802-text-index-weights/fundamentals/indexes/#text-indexes)
- [Text queries page](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-29802-text-index-weights/fundamentals/crud/read-operations/text/#examples)
=> DOCSP-29802: explain text index field weights

source/whats-new.txt
JIRA - [DOCSP-29819](https://jira.mongodb.org/browse/DOCSP-29819)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-29819-set-operator-issue-4.8/whats-new/#what-s-new-in-4.8
=> DOCSP-29819: type regression issue fixed in 4.8.1

source/faq.txt
JIRA - [DOCSP-29272](https://jira.mongodb.org/browse/DOCSP-29272)
[**Staging**](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-29272-pool-sizing-faq-fix/faq/#how-can-i-prevent-a-slow-operation-from-delaying-other-operations-)
=> DOCSP-29272: fix pool sizing question in faq

source/fundamentals/authentication/mechanisms.txt, source/whats-new.txt
JIRA - [DOCSP-26403](https://jira.mongodb.org/browse/DOCSP-26403)
Staging:
- [Auth page](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-26403-aws-sdk-changes/fundamentals/authentication/mechanisms/#mongodb-aws)
- [What's New](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-26403-aws-sdk-changes/whats-new/#what-s-new-in-4.11)
=> DOCSP-26403: changes to aws credential retrieval

source/connection-troubleshooting.txt, source/faq.txt, source/fundamentals/connection/connect.txt, source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-29488>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-29488/connection-troubleshooting/>
=> Docsp 29488 - Add Connection Troubleshooting Guide

source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30327>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-30327/>
=> DOCSP-30327: Added clear link for downloading and installing the driver

source/code-snippets/crud/cursor.js, source/code-snippets/indexes/listIndexes.js, source/code-snippets/indexes/listSearchIndexes.js, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30756>
Staging - 
[Cursor page](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-30756-add-listSearchIndexes-to-Cursor-pg/fundamentals/crud/read-operations/cursor/)
[Indexes](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-30756-add-listSearchIndexes-to-Cursor-pg/fundamentals/indexes/)
=> DOCSP-30756: add list search indexes to cursor page

source/code-snippets/indexes/listIndexes.js, source/fundamentals/indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30756>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-30756-listIndexes-v5.5-and-earlier/fundamentals/indexes/)
=> DOCSP-30756-listIndexes-v5.5-and-earlier

source/fundamentals/indexes.txt, source/quick-start.txt
While fixing the backport, I noticed there are errors in snooty when building from two targets not being found (see below) unrelated to my backport, so adding those as well.
ERROR(index.txt:30ish): Target not found: "label:node-quick-start-download-and-install"
ERROR(fundamentals/crud/read-operations/text.txt:59ish): Target not found: "label:node-fundamentals-text-indexes"
JIRA - <https://jira.mongodb.org/browse/DOCSP-30756>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-30756-4.5-through-4.0-backport/fundamentals/indexes/#list-indexes-1)
=> Docsp 30756 4.5 through 4.0 backport

source/fundamentals/crud/compound-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30891>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-30891-includeResultMetadata/fundamentals/crud/compound-operations/
=> DOCSP-30891: includeResultMetadata option

source/fundamentals/connection/connection-options.txt
** most of the work for this ticket was completed when the what's new was revised for v5.7 in #707 
JIRA - <https://jira.mongodb.org/browse/DOCSP-31156>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31156-wc-options-deprecated/fundamentals/connection/connection-options/#std-label-node-connection-options
=> DOCSP-31156: remove mentions of j,wtimeout, and fsync

source/upgrade.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-31720
Staging:
- [What's New](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-31720-remove-methods/whats-new/#what-s-new-in-6.0)
- [Upgrade](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-31720-remove-methods/upgrade/#version-6.x-breaking-changes)
=> docsp-31720 - remove deprecated helpers

source/whats-new.txt
Reworded admonition in 5.4 per Chris's comment from [this PR.](https://github.com/mongodb/docs-node/pull/729). Will be backported back through 5.4
=> reword admonition

source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection/tls.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31290>
Staging:
- [What's New](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31290-ssl-deprecation/whats-new/#what-s-new-in-6.0)
- [TLS page section](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31290-ssl-deprecation/fundamentals/connection/tls/#provide-certificate-filepaths)
- [auth page](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31290-ssl-deprecation/fundamentals/authentication/mechanisms/#tls-options)
=> DOCSP-31290: ssl options deprecated in v6.0

source/connection-troubleshooting.txt, source/fundamentals/crud/query-document.txt, source/whats-new.txt
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/FY2024Q3-typo-check/
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64d294bd67dbe91010fbfc29
=> DOCSP-32080 : typo check - FY2024Q3

source/upgrade.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31377>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31377-connection-pool-event-fields/whats-new/#what-s-new-in-6.0
**I also added something to the upgrade guide that I forgot to include in #731** - [staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31377-connection-pool-event-fields/upgrade/#version-6.x-breaking-changes)
=> DOCSP-31377: connection pool created event options v6

source/fundamentals/connection/connection-options.txt, source/fundamentals/connection/tls.txt, source/upgrade.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31483>
Staging:
- [whats new](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31483-cert-files-read-async/whats-new/#what-s-new-in-6.0)
- [upgrade](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31483-cert-files-read-async/upgrade/#version-6.x-breaking-changes)
- [TLS](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31483-cert-files-read-async/fundamentals/connection/tls/#provide-certificate-filepaths)
- [connection options](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31483-cert-files-read-async/fundamentals/connection/connection-opti …
=> DOCSP-31483: tls cert files read async v6

source/upgrade.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-31924
Staging -
[What's New ](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31924-move-clientEncryption/whats-new/#std-label-version-6.0)
[Upgrade](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31924-move-clientEncryption/upgrade/)
=> DOCSP-31924 mongodb-client-encryption changes for 6.0

snooty.toml, source/index.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-32433>
Staging:
- [What's New](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32433-v4.16-updates/whats-new/#std-label-version-4.16)
- [Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32433-v4.16-updates/quick-start/#add-mongodb-as-a-dependency)
=> DOCSP-32433: updates to v4.16 branch

source/fundamentals/transactions.txt, source/upgrade.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31847>
Staging
[whats new](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31847-client-session-error/whats-new/#what-s-new-in-6.0)
[upgrade](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31847-client-session-error/upgrade/#version-6.x-breaking-changes)
[txns page](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31847-client-session-error/fundamentals/transactions/#:~:text=Use%20a%20Session%20with%20the%20Client%20that%20Started%20It)
=> DOCSP-31847: use a session with the original client

source/fundamentals/crud/compound-operations.txt, source/upgrade.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31807>
Staging:
- [whats new](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31807-findone-behavior-change/whats-new/#what-s-new-in-6.0)
- [upgrade](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31807-findone-behavior-change/upgrade/#version-6.x-breaking-changes)
- [compound ops page admonition](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31807-findone-behavior-change/fundamentals/crud/compound-operations/#built-in-methods)
=> DOCSP-31807: includeResultMetadata option behavior changes for findOneAnd... methods

source/code-snippets/usage-examples/deleteMany.js, source/code-snippets/usage-examples/deleteMany.ts
https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-32718-deletemany-comments/usage-examples/deleteMany/
=> DOCSP-32718: deletemany UE code comments

source/code-snippets/usage-examples/count.js
https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-32718-count-comments/usage-examples/count/
=> DOCSP-32718: count UE code comments

source/code-snippets/usage-examples/deleteOne.js
https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-32718-deleteone-comments/usage-examples/deleteOne/
=> DOCSP-32718: deleteone UE code comments

source/code-snippets/crud/startrek.js, source/code-snippets/monitoring/apm-subscribe.js, source/code-snippets/monitoring/cpm-subscribe.js, source/code-snippets/monitoring/sdam-subscribe.js, source/code-snippets/usage-examples/changeStream_listener.js, source/code-snippets/usage-examples/command.js, source/code-snippets/usage-examples/updateMany.js, source/code-snippets/usage-examples/updateMany.ts
JIRA - https://jira.mongodb.org/browse/DOCSP-32718
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32718-code-commenting/
=> Added code comments

source/code-snippets/usage-examples/updateOne.js, source/code-snippets/usage-examples/updateOne.ts
https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-32718-updateone-comments/usage-examples/updateOne/
=> DOCSP-32718: updateone UE code comments

source/code-snippets/aggregation/agg.js
https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-32718-aggregation-comments/fundamentals/aggregation/
=> DOCSP-32718: aggregation code comments

source/code-snippets/indexes/geo.js
=> DOCSP-32718: geo index code comments

source/code-snippets/indexes/listIndexes.js
https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-32718-listindexes-comments/fundamentals/indexes/#list-indexes
=> DOCSP-32718: listindexes code comments

source/code-snippets/usage-examples/insertOne.js
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32718-insertOne-comments/usage-examples/insertOne/>
=> DOCSP-32718: insertOne comments

source/code-snippets/usage-examples/bulkWrite.js
Pull Request Info
JIRA - https://jira.mongodb.org/browse/DOCSP-32718
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32718-code-whisperer-bulk-write/usage-examples/bulkWrite/
=> Docsp 32718 code whisperer bulk write

source/code-snippets/crud/arrayFilters.js, source/code-snippets/indexes/text.js, source/code-snippets/monitoring/cpm-subscribe.js, source/code-snippets/usage-examples/distinct.js, source/code-snippets/usage-examples/find.js, source/code-snippets/usage-examples/findOne.js, source/code-snippets/usage-examples/insertMany.js, source/code-snippets/usage-examples/replaceOne.js, source/fundamentals/crud/write-operations/embedded-arrays.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-32718
Staging:
- [Arrays](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-32718-code-whisperer-comments/fundamentals/crud/write-operations/embedded-arrays/)
- [Text Indexes](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-32718-code-whisperer-comments/fundamentals/indexes/#text-indexes)
- [CPM Events](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-32718-code-whisperer-comments/fundamentals/monitoring/connection-monitoring/)
- [Find One](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-32718-code-whisperer-comments/usage-examples/findOne/) …
=> docsp-32718 - add comments

source/code-snippets/crud/startrek.js, source/code-snippets/monitoring/apm-subscribe.js, source/code-snippets/monitoring/cpm-subscribe.js, source/code-snippets/monitoring/sdam-subscribe.js, source/code-snippets/usage-examples/changeStream_listener.js, source/code-snippets/usage-examples/command.js, source/code-snippets/usage-examples/updateMany.js, source/code-snippets/usage-examples/updateMany.ts
(cherry picked from commit 5b0652a7a3338f73731150eed574a39fa2320b7c)
=> Added code comments (#772)

source/code-snippets/collation/aggregation-collation.js, source/code-snippets/collation/collection-auto-collation.js, source/code-snippets/collation/collection-collation.js, source/code-snippets/collation/collection-specify-collation.js, source/code-snippets/collation/find-sort-collation.js, source/code-snippets/collation/findOneAndDelete-collation.js, source/code-snippets/collation/findOneAndDelete-no-collation.js, source/code-snippets/collation/findOneAndUpdate-collation.js, source/code-snippets/collation/findOneAndUpdate-default-order-collation.js, source/code-snippets/collation/index-collation.js, source/code-snippets/collation/query-index-collation.js, source/code-snippets/collation/query-index-no-collation.js, source/code-snippets/collation/query-not-indexed-collation.js, source/fundamentals/collations.txt
Staging - 
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32718-collation-snippets/fundamentals/collations/
=> DOCSP-32718: add CodeWhisperer comments to collation code snippets

source/code-snippets/connection/socks.js
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32718-socks5-snippet/fundamentals/connection/socks/
=> DOCSP-32718: add CodeWhisperer comments to SOCKS5 code snippet

source/code-snippets/transactions/txn-core.js, source/fundamentals/transactions.txt
Staging -  https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32718-transactions/fundamentals/transactions/
=> DOCSP-32718: add CodeWhisperer comments to transactions code snippets

source/upgrade.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-32548>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32548-consolidate-breaking/whats-new/>
=> DOCSP-32548: Breaking changes consolidation

source/upgrade.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31571>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCPS-31571-upgrade-instructions/upgrade/>
=> DOCPS-31571: Add upgrade information

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
**JIRA Tickets**
https://jira.mongodb.org/browse/DOCSP-32271
https://jira.mongodb.org/browse/DOCSP-32273
https://jira.mongodb.org/browse/DOCSP-32274
https://jira.mongodb.org/browse/DOCSP-32275
https://jira.mongodb.org/browse/DOCSP-32294
https://jira.mongodb.org/browse/DOCSP-32306
https://jira.mongodb.org/browse/DOCSP-32305
https://jira.mongodb.org/browse/DOCSP-32307
**Staging**
https://preview-mongodbsarahsimpers.gatsbyjs.io/node/DOCSP-32271/
https://preview-mongodbsarahsimpers.gatsbyjs.io/node/DOCSP-32271/fundamentals/connection/
https://preview-mongodbsarahsimpers.gatsbyjs.io/node/DOCSP-32271/fundamentals/crud/
https://preview-mongodbsarahsimpers.gatsbyjs.io/node/DOCSP-32271/fundamentals/crud/read-op …
=> (DOCSP-32271) Adds Atlas CTA to several Node.js pages

source/fundamentals/crud/compound-operations.txt
**this PR can only be merged to v6.0+ because of the value of the default. When backporting, I will rearrange the information so that the correct default is described for pre-v6 versions**
JIRA - <https://jira.mongodb.org/browse/DOCSP-32806>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-32806-metadata-content/fundamentals/crud/compound-operations/
=> DOCSP-32806: metadata option for compound methods

source/fundamentals/crud/compound-operations.txt
**FOR V5.8 and V5.7** #808
JIRA - <https://jira.mongodb.org/browse/DOCSP-32806>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/node/v5.8/fundamentals/crud/compound-operations/#includeresultmetadata-option
=> DOCSP-32806: metadata option for compound methods (#808)

source/code-snippets/crud/pizza.js, source/fundamentals/crud/read-operations/retrieve.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35143>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/node/DOCSP-35143-remove-await/fundamentals/crud/read-operations/retrieve/>
=> DOCSP-35143: Remove await operators

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v6.3`:
=> [v6.3] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v6.2`:
=> [v6.2] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v6.0`:
=> [v6.0] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v5.9`:
=> [v5.9] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v5.8`:
=> [v5.8] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v5.7`:
=> [v5.7] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v5.6`:
=> [v5.6] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v5.5`:
=> [v5.5] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v5.4`:
=> [v5.4] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v5.3`:
=> [v5.3] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v5.2`:
=> [v5.2] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v5.1`:
=> [v5.1] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
=> [v5.0] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
This will backport the following commits from `master` to `v4.15`:
=> [v4.15] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
=> [v4.14] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
=> [v4.13] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
=> [v4.12] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
=> [v4.11] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
=> [v4.10] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
=> [v4.9] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/cluster-monitoring.txt
=> [v4.8] DOCSP-35296 Fix swapped link text (#844)

source/fundamentals/monitoring/command-monitoring.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35195>
Staging - 
[CommandSucceeded](https://preview-mongodbcchomongodb.gatsbyjs.io/node/DOCSP-35195-fix-duration/fundamentals/monitoring/command-monitoring/#commandsucceeded)
[CommandFailed](https://preview-mongodbcchomongodb.gatsbyjs.io/node/DOCSP-35195-fix-duration/fundamentals/monitoring/command-monitoring/#commandfailed)
=> DOCSP-35195: fix duration values

source/fundamentals/connection/connection-options.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35367>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-35367-remove-timeoutms-opt/fundamentals/connection/connection-options/
=> DOCSP-35367: remove unsupported single timeout option

source/fundamentals/crud/write-operations/modify.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37358>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/node/DOCSP-37358-modify-instruqt-changes/fundamentals/crud/write-operations/modify/>
=> DOCSP-37358: Modify guide Instruqt updates

source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37612>
Staging - [Compatibility](https://preview-mongodbcchomongodb.gatsbyjs.io/node/DOCSP-37612-compat-shared-include/compatibility/#compatibility-table-legend)
=> DOCSP-37612: convert compatibility to sharedinclude

source/code-snippets/indexes/searchIndexes.js, source/fundamentals/indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37442>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-37442-show-vector-idx-creation/fundamentals/indexes/#create-a-search-index>
[log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f1b42e6fc5f0485016cf06)
=> DOCSP-37442: show vector search idx creation

source/aggregation-tutorials/filtered-subset.txt, source/upgrade.txt, source/whats-new.txt
Note: all breaking changes were introduced in major versions, so ".x" has been changed to ".0".
JIRA - https://jira.mongodb.org/browse/DOCSP-32561
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/node/DOCSP-32561-exact-versions/upgrade/
=> DOCSP-32561: Exact versions in upgrade guide

source/code-snippets/monitoring/cpm-status.js, source/fundamentals/monitoring/connection-monitoring.txt
Paraphrased from requester: "The context here is to showcase a practical example of what CMAP monitoring could be used for – the existing "Event Subscription Example" shows how to subscribe, but not really why you'd bother in the first place."
Code sample provided by requester and tested by me (with comments added).
JIRA - <https://jira.mongodb.org/browse/DOCSP-38042>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/node/DOCSP-38042-connection-tracking/fundamentals/monitoring/connection-monitoring/>
=> DOCSP-38042: CMAP Tracking Example

source/fundamentals/authentication.txt, source/fundamentals/authentication/enterprise-mechanisms.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39361
Staging - https://preview-mongodbmongokart.gatsbyjs.io/node/docsp-39361-oidc/fundamentals/authentication/enterprise-mechanisms/#mongodb-oidc
=> DOCSP-39361 - OIDC

source/faq.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-40094
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/node/DOCSP-40094-close-behavior/faq/#how-does-connection-pooling-work-in-the-node-driver-
=> DOCSP-40094: Clarify MongoClient.close() behavior

source/code-snippets/authentication/cr.js, source/code-snippets/authentication/default.js, source/code-snippets/authentication/sha1.js, source/code-snippets/authentication/sha256.js, source/connection-troubleshooting.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-42373
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/node/DOCSP-42373-update-placeholders/
=> DOCSP-42373 Update username and password placeholders

source/code-snippets/monitoring/apm-subscribe.js
Fixing sample per guidance provided in Jira ticket. Plan is to backport this as far back as v6.4.0
JIRA - <https://jira.mongodb.org/browse/DOCSP-42530>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/node/DOCSP-42530-monitoring-sample/fundamentals/monitoring/command-monitoring/>
=> DOCSP-42530: Fix command monitoring code sample

config/redirects, snooty.toml, source/fundamentals/monitoring/connection-monitoring.txt, source/includes/mongodb-compatibility-table-node.rst, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-43533
Staging:
- [What's New](https://deploy-preview-902--docs-node.netlify.app/whats-new/#std-label-version-6.9)
- [Compatibility](https://deploy-preview-902--docs-node.netlify.app/compatibility/#footnote-deprecated)
=> DOCSP-43533 - Version 6.9

source/fundamentals/bson/utf8-validation.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43242>
Staging - <https://deploy-preview-908--docs-node.netlify.app/fundamentals/bson/utf8-validation/>
=> DOCSP-43242: Improve UTF-8 validation documentation to clarify validation occurs on decoded data only

source/fundamentals/connection/connection-options.txt
Remove deprecated options and include better intro that explains that the page documents options passed to a ``MongoClientOptions`` instance. 
JIRA - <https://jira.mongodb.org/browse/DOCSP-31359>
Staging - <https://deploy-preview-941--docs-node.netlify.app/fundamentals/connection/connection-options/>
=> DOCSP-31359 Revise Connection Options

source/fundamentals/connection/tls.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-38014>
Staging - <https://deploy-preview-942--docs-node.netlify.app/fundamentals/connection/tls/>
=> DOCSP-38014 SSL Error Workaround

source/fundamentals/connection/connection-options.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41823>
Staging - <https://deploy-preview-944--docs-node.netlify.app/fundamentals/connection/connection-options/>
=> DOCSP-41823: `autoSelectFamily` and `autoSelectFamilyAttemptTimeout` options

source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43243>
Staging - <https://deploy-preview-943--docs-node.netlify.app/compatibility/>
=> DOCSP-43243 Clarify driver support for language versions

source/fundamentals/authentication/enterprise-mechanisms.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44256>
Staging - <https://deploy-preview-950--docs-node.netlify.app/fundamentals/authentication/enterprise-mechanisms/#kubernetes>
=> DOCSP-44256 Add Kubernetes Support for OIDC

source/fundamentals/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45876>
Staging - <https://deploy-preview-952--docs-node.netlify.app/fundamentals/transactions/>
=> DOCSP-45876 Add parallel operations callout

source/code-snippets/crud/bulk.js, source/fundamentals/crud/write-operations.txt, source/fundamentals/crud/write-operations/bulk.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34101>
Staging - <https://deploy-preview-948--docs-node.netlify.app/fundamentals/crud/write-operations/bulk/>
=> DOCSP-34101-create-bulk-operations-page

source/faq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46471>
Staging - <https://deploy-preview-954--docs-node.netlify.app/faq/>
=> DOCSP-46471: Fix 404 link

.github/workflows/vale-tdbx.yml, source/code-snippets/connection/csot-operation.js, source/code-snippets/connection/csot.js, source/fundamentals/connection.txt, source/fundamentals/connection/csot.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44666>
Staging - <https://deploy-preview-951--docs-node.netlify.app/fundamentals/connection/csot/>
=> DOCSP-4466 Add CSOT

source/fundamentals/logging.txt, source/includes/fundamentals/logging.js, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-46811
Staging - https://deploy-preview-981--docs-node.netlify.app/fundamentals/logging/
=> DOCSP-46811 Standardized Logger

source/code-snippets/crud/bulk.js, source/fundamentals/crud/write-operations/bulk.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-44681
Staging - https://deploy-preview-984--docs-node.netlify.app/fundamentals/crud/write-operations/bulk/
=> DOCSP-44681: Client bulk write

source/fundamentals/run-command.txt, source/usage-examples/command.txt
This will backport the following commits from `master` to `v6.14`:
=> [v6.14] DOCSP-46758 Change Run Command page title (#1009)

source/fundamentals/run-command.txt, source/usage-examples/command.txt
This will backport the following commits from `master` to `v6.12`:
=> [v6.12] DOCSP-46758 Change Run Command page title (#1009)

source/fundamentals/run-command.txt, source/usage-examples/command.txt
This will backport the following commits from `master` to `v6.11`:
=> [v6.11] DOCSP-46758 Change Run Command page title (#1009)

source/fundamentals/run-command.txt, source/usage-examples/command.txt
This will backport the following commits from `master` to `v6.10`:
=> [v6.10] DOCSP-46758 Change Run Command page title (#1009)

source/fundamentals/run-command.txt, source/usage-examples/command.txt
This will backport the following commits from `master` to `v6.8`:
=> [v6.8] DOCSP-46758 Change Run Command page title (#1009)

source/fundamentals/run-command.txt, source/usage-examples/command.txt
This will backport the following commits from `master` to `v6.7`:
=> [v6.7] DOCSP-46758 Change Run Command page title (#1009)

source/fundamentals/run-command.txt, source/usage-examples/command.txt
This will backport the following commits from `master` to `v6.6`:
=> [v6.6] DOCSP-46758 Change Run Command page title (#1009)

source/fundamentals/run-command.txt, source/usage-examples/command.txt
This will backport the following commits from `master` to `v6.5`:
=> [v6.5] DOCSP-46758 Change Run Command page title (#1009)

source/fundamentals/run-command.txt, source/usage-examples/command.txt
This will backport the following commits from `master` to `v6.4`:
=> [v6.4] DOCSP-46758 Change Run Command page title (#1009)

source/fundamentals/run-command.txt, source/usage-examples/command.txt
This will backport the following commits from `master` to `v6.3`:
=> [v6.3] DOCSP-46758 Change Run Command page title (#1009)

source/atlas-search.txt, source/includes/atlas-search.js, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48384
Staging - https://deploy-preview-1041--docs-node.netlify.app/atlas-search/
=> DOCSP-48384: Atlas search

source/connect/mongoclient.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48378>
Staging - <https://deploy-preview-1038--docs-node.netlify.app/connect/mongoclient/>
=> DOCSP-48378 make mongoclient page

source/databases-collections.txt, source/includes/databases-collections.js, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-48493
Staging - https://deploy-preview-1045--docs-node.netlify.app/databases-collections/
=> DOCSP-48493: Databases & collections

source/atlas-search.txt, source/atlas-vector-search.txt, source/code-snippets/indexes/searchIndexes.js, source/indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48608>
https://deploy-preview-1065--docs-node.netlify.app/indexes/#atlas-search-and-atlas-vector-search-indexes
=> DOCSP-48608 Edit AVS and AS section on Indexes page

source/connect/connection-options/connection-pools.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48683>
[Manage Connections with Connection Pools](https://deploy-preview-1067--docs-node.netlify.app/connect/connection-options/connection-pools/)
=> DOCSP-48683 Refine Connection Pools page

source/crud/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48501>
Staging - <https://deploy-preview-1047--docs-node.netlify.app/crud/transactions/#causal-consistency>
=> DOCSP-48501 add casual consistency section

source/crud/query/count.txt, source/crud/query/retrieve.txt, source/crud/query/specify-documents-to-return.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48707>
https://deploy-preview-1073--docs-node.netlify.app/crud/query/specify-documents-to-return/#combine-limit--sort--and-skip
=> DOCSP-48707 Standardize cursor chaining methods

config/redirects
JIRA - N/A
Versions 6.13-6.15 will need separate backports so they don't include the newer versions.
No pages to preview
=> [Node] Bug fix: Add v to version numbers

config/redirects
Backport of https://github.com/mongodb/docs-node/pull/1103 to v6.13
=> Fix redirects for v6.13

source/crud/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35201>
[crud/transactions/#transaction-errors](https://deploy-preview-1164--docs-node.netlify.app/crud/transactions/#:~:text=(txnOpts)%3B-,Transaction%20Errors,-Because%20MongoDB%20transactions)
=> DOCSP-35201 Transaction Retry Logic in Core API

.backportrc.json, source/connect/connection-options/csot.txt, source/connect/mongoclient.txt, source/crud/query/cursor.txt, source/crud/transactions.txt, source/crud/transactions/transaction-core.txt, source/includes/explicit-resource-management.rst, source/monitoring-and-logging/change-streams.txt
Added tips to certain pages that introduce resources covered by ERM. Limited inclusion to intro pages, but can extend tips to any instance of ``MongoClient`` and other resources being created (this would be a lot of pages, not sure if action needed everywhere considering most pages link back to intro reference page when resource is used in example).
JIRA - <https://jira.mongodb.org/browse/DOCSP-41784>
<li><a href=https://deploy-preview-1165--docs-node.netlify.app/connect/mongoclient>connect/mongoclient</a></li><li><a href=https://deploy-preview-1165--docs-node.netlify.app/crud/query/cursor>crud/query/cursor</a></li><li><a href=https://deploy-preview-1165--docs-node.netlify.app/crud/transactions>crud/tr …
=> DOCSP-41784 Support for Explicit Resource Management 

.backportrc.json, source/connect/mongoclient.txt, source/crud/query/cursor.txt, source/crud/transactions.txt, source/crud/transactions/transaction-core.txt, source/includes/explicit-resource-management.rst, source/monitoring-and-logging/change-streams.txt
This will backport the following commits from `master` to `v6.17`:
- [DOCSP-41784 Support for Explicit Resource Management  (#1165)](https://github.com/mongodb/docs-node/pull/1165)
=> [v6.17] DOCSP-41784 Support for Explicit Resource Management  (#1165)

snooty.toml, source/aggregation.txt, source/aggregation/pipeline-stages.txt
This will backport the following commits from `master` to `v6.15`:
=> [v6.15] DOCSP-50497 Node Aggregation Standardization (#1176)

snooty.toml, source/aggregation.txt, source/aggregation/pipeline-stages.txt
This will backport the following commits from `master` to `v6.13`:
=> [v6.13] DOCSP-50497 Node Aggregation Standardization (#1176)

snooty.toml, source/aggregation.txt, source/aggregation/pipeline-stages.txt
This will backport the following commits from `master` to `v6.12`:
=> [v6.12] DOCSP-50497 Node Aggregation Standardization (#1176)

snooty.toml, source/aggregation.txt, source/aggregation/pipeline-stages.txt
This will backport the following commits from `master` to `v6.10`:
=> [v6.10] DOCSP-50497 Node Aggregation Standardization (#1176)

snooty.toml, source/aggregation.txt, source/aggregation/pipeline-stages.txt
This will backport the following commits from `master` to `v6.9`:
=> [v6.9] DOCSP-50497 Node Aggregation Standardization (#1176)

source/indexes.txt, source/reference/quick-reference.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-50491>
<li><a href=https://deploy-preview-1188--docs-node.netlify.app/indexes>indexes</a></li><li><a href=https://deploy-preview-1188--docs-node.netlify.app/reference/quick-reference>reference/quick-reference</a></li>
=> DOCSP-50491 Clean up Quick Ref page

source/includes/try-next-warning.rst, source/monitoring-and-logging/change-streams.txt
This will backport the following commits from `master` to `v6.17`:
=> [v6.17] DOCSP-51959 Add a warning about tryNext bug to all change stream manual iteration examples (#1189)

source/includes/try-next-warning.rst, source/monitoring-and-logging/change-streams.txt
This will backport the following commits from `master` to `v6.16`:
=> [v6.16] DOCSP-51959 Add a warning about tryNext bug to all change stream manual iteration examples (#1189)

source/includes/try-next-warning.rst, source/monitoring-and-logging/change-streams.txt
This will backport the following commits from `master` to `v6.14`:
=> [v6.14] DOCSP-51959 Add a warning about tryNext bug to all change stream manual iteration examples (#1189)

source/includes/try-next-warning.rst, source/monitoring-and-logging/change-streams.txt
This will backport the following commits from `master` to `v6.13`:
=> [v6.13] DOCSP-51959 Add a warning about tryNext bug to all change stream manual iteration examples (#1189)

source/includes/try-next-warning.rst, source/monitoring-and-logging/change-streams.txt
This will backport the following commits from `master` to `v6.12`:
=> [v6.12] DOCSP-51959 Add a warning about tryNext bug to all change stream manual iteration examples (#1189)

source/includes/try-next-warning.rst, source/monitoring-and-logging/change-streams.txt
This will backport the following commits from `master` to `v6.9`:
=> [v6.9] DOCSP-51959 Add a warning about tryNext bug to all change stream manual iteration examples (#1189)

source/connect/connection-options/connection-pools.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-51630>
<li><a href=https://deploy-preview-1190--docs-node.netlify.app/connect/connection-options/connection-pools>connect/connection-options/connection-pools</a></li>
=> DOCSP-51630 Add admonition for minPoolSize behavior
