source/code-snippets/usage-examples/findOne.js, source/usage-examples/findOne.txt
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker/DOCSP-7598x2/usage-examples/findOne
=> DOCSP-7598: standardize findOne with find

source/code-snippets/usage-examples/deleteMany.js, source/usage-examples.txt, source/usage-examples/deleteMany.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-7607
staging: https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker/DOCSP-7607/usage-examples/deleteMany
=> DOCSP-7607: Delete multiple documents usage example

.eslintrc, .gitignore, .prettierrc, source/code-snippets/usage-examples/deleteMany.js, source/code-snippets/usage-examples/deleteOne.js, source/code-snippets/usage-examples/find.js, source/code-snippets/usage-examples/findOne.js, source/code-snippets/usage-examples/findOneAndDelete.js, source/getting-started.txt, source/usage-examples.txt
Also apparently makes a few linter updates.
Staged: https://docs-mongodborg-staging.corp.mongodb.com/node/docsworker/tweaks/
=> Tweaks to improve user friendliness & exclude vscode from git

source/code-snippets/usage-examples/insertMany.js, source/usage-examples.txt, source/usage-examples/insertMany.txt
Ticket: https://jira.mongodb.org/browse/DOCSP-7601
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker/DOCSP-7601-insertMany/usage-examples/insertMany
=> Docsp 7601 insert many

.gitignore, conf.py, source/code-snippets/usage-examples/bulkWrite-example.js, source/usage-examples.txt, source/usage-examples/bulkWrite.txt
jira: https://jira.mongodb.org/browse/DOCSP-7602
staged: https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker/DOCSP-7602/usage-examples/bulkWrite
=> DOCSP-7602: adds bulkWrite usage example

source/code-snippets/usage-examples/count.js, source/usage-examples.txt, source/usage-examples/count.txt
Jira: https://jira.mongodb.org/browse/DOCSP-7609
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker/DOCSP-7609/usage-examples/count
=> DOCSP-7609: adds countDocuments and estimatedDocumentCount examples

source/code-snippets/usage-examples/replaceOne.js, source/usage-examples.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateOne.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-7605
Stage: https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker/DOCSP-7605/usage-examples/replaceOne
=> (DOCSP-7605): replace a document

source/includes/language-compatibility-table-node.rst, source/includes/mongodb-compatibility-table-node.rst, source/includes/unicode-checkmark.rst, source/index.txt
Please review [staged](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker/DOCSP-8296/#compatibility)
=> (DOCSP-8296) - add compat tables to node driver

source/code-snippets/usage-examples/command.js, source/usage-examples.txt, source/usage-examples/command.txt, source/usage-examples/missing-link.txt
Stage:
------
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-8054-Run-a-Command-Usage/usage-examples/command
JIRA:
-----
https://jira.mongodb.org/browse/DOCSP-8054
=> Docsp 8054 run a command usage

source/code-snippets/crud/startrek.js, source/code-snippets/crud/theaters.js, source/code-snippets/usage-examples/find.js, source/code-snippets/usage-examples/insertMany.js, source/code-snippets/usage-examples/insertOne.js
Fixed a couple of comment typos/improved them and switched the find example to use `count()` instead of `hasNext()` which can cause serious issues due to caching.
=> chore: improve a couple of code examples

source/code-snippets/usage-examples/deleteMany.js, source/code-snippets/usage-examples/deleteOne.js, source/code-snippets/usage-examples/findOneAndDelete.js
stage: https://docs-mongodborg-staging.corp.mongodb.com/node/docsworker/callbackz/
=> u ain't nothin but a callback

source/crud.txt, source/usage-examples.txt, source/usage-examples/command.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
and miscellaneous cleanup
stage: https://docs-mongodborg-staging.corp.mongodb.com/node/docsworker/titleUniformity/
=> organizing examples section

source/usage-examples/distinct.txt
Found a minor monospace word formatting issue I introduced while cleaning up some of the pages.
=> fix formatting issue

source/code-snippets/faq/econnresetWithClientConnect-example.js, source/code-snippets/faq/maxTimeMS-example.js
Changes:
----------
* Upgrade FAQ page code snippet to es6 syntax
* Upgrade FAQ page to use async/await syntax 
Stage:
------
https://docs-mongodbcom-staging.corp.mongodb.com/3879926/node/docsworker-xlarge/Moe-FAQ-Syntax-Improvements/faq
=> (unticketed):FAQ syntax improvements - upgrade to es6 & async/await syntax

source/code-snippets/crud/arrayFilters.js, source/code-snippets/crud/cursor.js, source/code-snippets/crud/pizza.js, source/code-snippets/crud/startrek.js, source/code-snippets/crud/theaters.js
JIRA: https://jira.mongodb.org/browse/DOCSP-8860
No staging -- just a background fix.
The Atlas cluster's credentials have been changed.
=> (DOCSP-8860: Remove credentials from code snippet files

source/fundamentals/authentication/enterprise-mechanisms.txt, source/fundamentals/authentication/mechanisms.txt
JIRA: https://jira.mongodb.org/browse/DOCSP-9032
Staging:
- [Mechanisms](https://docs-mongodbcom-staging.corp.mongodb.com/947c4ce/node/docsworker-xlarge/DOCSP-9032-feedback-auth-guide/fundamentals/authentication/mechanisms)
- [Enterprise Mechanisms](https://docs-mongodbcom-staging.corp.mongodb.com/947c4ce/node/docsworker-xlarge/DOCSP-9032-feedback-auth-guide/fundamentals/authentication/enterprise-mechanisms)
=> DOCSP-9032: feedback fixes for auth guides

README.rst
JIRA: https://jira.mongodb.org/browse/DOCSP-9615
=> DOCSP-9615: remove broken and irrelevant links from README

source/code-snippets/authentication/aws.js, source/code-snippets/authentication/cr.js, source/code-snippets/authentication/default.js, source/code-snippets/authentication/sha1.js, source/code-snippets/authentication/sha256.js, source/code-snippets/authentication/x509.js, source/fundamentals/authentication/mechanisms.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-9407
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/cb20788/node/docsworker-xlarge/DOCSP-9407-aws-auth/fundamentals/authentication/mechanisms#mongodb-aws
=> DOCSP-9407: Add MONGODB-AWS auth mechanism

source/code-snippets/usage-examples/insertMany.js, source/code-snippets/usage-examples/updateOne.js, source/includes/connect-guide-note.rst, source/usage-examples/bulkWrite.txt, source/usage-examples/command.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-9034
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/87ed1d4/node/docsworker-xlarge/DOCSP-9034-feedback-usage-examples/
=> DOCSP-9034: feedback usage examples

source/code-snippets/crud/pizza.js, source/code-snippets/usage-examples/bulkWrite-example.js, source/fundamentals/logging.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-9040
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/382bad5/node/docsworker-xlarge/DOCSP-9040-arrow-functions/
=> DOCSP-9040: convert remaining anon functions to arrow ones

source/fundamentals/crud/read-operations/sort.txt
JIRA: 
https://jira.mongodb.org/browse/DOCSP-9536
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/f20a7c5/node/docsworker-xlarge/DOCSP-9536-sort-updates/
=> DOCSP-9536: remove server doc link from sort page

source/index.txt, source/issues-and-help.txt
JIRA: 
https://jira.mongodb.org/browse/DOCSP-9028
Staging:
index page: https://docs-mongodborg-staging.corp.mongodb.com/6664b62/node/docsworker-xlarge/DOCSP-9028-index-page-fixes/
issues and help page: https://docs-mongodborg-staging.corp.mongodb.com/6664b62/node/docsworker-xlarge/DOCSP-9028-index-page-fixes/issues-and-help
=> DOCSP-9028: index page and issues and help page fixes

source/quick-start.txt
No JIRA
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/8fa9c1f/node/docsworker-xlarge/preview-040120/
=> directive and grammar fixes to quick-start

source/usage-examples.txt
JIRA: 
None
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/ab61ef3/node/docsworker-xlarge/040720-fix-guide-link/usage-examples
=> Fix guide link in usage examples landing page

source/usage-examples/findOne.txt
JIRA: none
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/d4fd024/node/docsworker-xlarge/040820-find-descending/usage-examples/findOne
=> Fix language around findOne sort: ascending -> descending

source/fundamentals.txt, source/fundamentals/promises.txt, source/index.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-9706
Staging:
Changes to Index Page:
https://docs-mongodbcom-staging.corp.mongodb.com/3de88bd/node/docsworker/DOCSP-9706-promises/
Fundamentals > Promises and Callbacks:
https://docs-mongodbcom-staging.corp.mongodb.com/3de88bd/node/docsworker/DOCSP-9706-promises/fundamentals/promises
=> DOCSP-9706: Promises and Callbacks

snooty.toml, source/faq.txt, source/fundamentals/authentication.txt, source/fundamentals/connection.txt, source/fundamentals/indexes.txt, source/fundamentals/promises.txt, source/usage-examples/command.txt
JIRA: 
https://jira.mongodb.org/browse/DOCSP-10080
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/04b6a02/node/docsworker/DOCSP-10080-node-js/
=> DOCSP-10080: Replace NodeJS with Node.js

source/fundamentals/collations.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10136
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/6144222/node/docsworker/DOCSP-10136-node-docs-collations/fundamentals/collations
=> DOCSP-10136: replace with code-block

source/fundamentals/crud/read-operations/skip.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10101
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/9219940/node/docsworker/DOCSP-10101-feedback-skip-results/fundamentals/crud/read-operations/skip
=> DOCSP-10101: feedback fixes for skip results

source/fundamentals/crud/read-operations/geo.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10220
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/9f8226a/node/docsworker/DOCSP-10220-feedback-geospatial/fundamentals/crud/read-operations/geo
=> DOCSP-10220: feedback fixes for geospatial queries

source/code-snippets/crud/startrek.js, source/fundamentals/crud/read-operations/text.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10237
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/d968813/node/docsworker/DOCSP-10237-feedback-text-search/fundamentals/crud/read-operations/text
=> DOCSP-10237: address feedback on text search

source/code-snippets/crud/cursor.js, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/cursor.txt
JIRA: 
https://jira.mongodb.org/browse/DOCSP-10199
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/5c09684/node/docsworker/DOCSP-10199-feedback-cursor/fundamentals/crud/read-operations/cursor
=> DOCSP-10199: cursor feedback fixes

source/fundamentals/crud/write-operations/upsert.txt
JIRA: 
https://jira.mongodb.org/browse/DOCSP-10319
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/58f4691/node/docsworker/DOCSP-10319-insert-or-update/fundamentals/crud/write-operations/upsert
=> DOCSP-10319: address feedback on insert or update

source/fundamentals/crud/write-operations/change-a-document.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10317
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/ba19462/node/docsworker/DOCSP-10317-feedback-change-document/fundamentals/crud/write-operations/change-a-document
=> DOCSP-10317: address feedback on Change a Document

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/geo.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/code-snippets/indexes/unique.js, source/fundamentals/indexes.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10341
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/b675bbd/node/docsworker/DOCSP-10341-feedback-indexes/fundamentals/indexes
=> DOCSP-10341: feedback fixes for indexes

source/usage-examples/findOne.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10371
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/5fe6a8d/node/docsworker/DOCSP-10371-feedback-usage-example-find-document/usage-examples/findOne
=> DOCSP-10371: address feedback on findOne usage example

source/code-snippets/usage-examples/count.js, source/usage-examples/count.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10386
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/24010a1/node/docsworker/DOCSP-10386-feedback-count/usage-examples/count
=> DOCSP-10386: address feedback on Count documentation

source/code-snippets/usage-examples/find.js, source/usage-examples/find.txt, source/usage-examples/findOne.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10384
Staging:
Find Many
https://docs-mongodbcom-staging.corp.mongodb.com/58546c1/node/docsworker/DOCSP-10384-feedback-usage-example-find-many/usage-examples/find
Find One
https://docs-mongodbcom-staging.corp.mongodb.com/58546c1/node/docsworker/DOCSP-10384-feedback-usage-example-find-many/usage-examples/findOne
=> DOCSP-10384: feedback usage example find many

source/code-snippets/usage-examples/distinct.js, source/usage-examples/distinct.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10420
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/9377490/node/docsworker/DOCSP-10420-feedback-distinct/usage-examples/distinct
=> DOCSP-10420: address feedback on distinct usage example

source/usage-examples/command.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10421
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/9210614/node/docsworker/DOCSP-10421-feedback-command/
=> DOCSP-10421: address feedback on command usage example

source/code-snippets/usage-examples/changeStream.js, source/usage-examples/changeStream.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10436
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/f02dacb/node/docsworker/DOCSP-10436-feedback-change-streams/usage-examples/changeStream
=> DOCSP-10436: address feedback on change streams usage example

source/usage-examples/bulkWrite.txt, source/usage-examples/command.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10430
Staging:
Multiple pages under section:
https://docs-mongodbcom-staging.corp.mongodb.com/e3a8e5a/node/docsworker/DOCSP-10430-promise-note/usage-examples
=> DOCSP-10430: update note on promises

source/faq.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10459
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/d719551/node/docsworker/DOCSP-10459-feedback-faq/faq
=> DOCSP-10459: address feedback on FAQ

source/fundamentals/connection.txt, source/fundamentals/crud/read-operations/text.txt, source/includes/atlas-search.rst, source/quick-start.txt, source/usage-examples.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-10565
Staging:
[Text Search](https://docs-mongodbcom-staging.corp.mongodb.com/e5dbbc7/node/docsworker/DOCSP-10565-atlas-mention-fts/fundamentals/crud/read-operations/text)
[Quick Start](https://docs-mongodbcom-staging.corp.mongodb.com/e5dbbc7/node/docsworker/DOCSP-10565-atlas-mention-fts/quick-start)
[Usage Examples](https://docs-mongodbcom-staging.corp.mongodb.com/e5dbbc7/node/docsworker/DOCSP-10565-atlas-mention-fts/usage-examples)
[Connection Guide](https://docs-mongodbcom-staging.corp.mongodb.com/e5dbbc7/node/docsworker/DOCSP-10565-atlas-mention-fts/fundamentals/connection)
=> DOCSP-10565: add atlas ad

source/faq.txt, source/fundamentals/crud/read-operations/cursor.txt, source/index.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-11501
=> update the API link to point to 3.6 driver docs

source/fundamentals/authentication.txt, source/fundamentals/authentication/mechanisms.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-11519
Staging:
[Authentication Landing Page](https://docs-mongodbcom-staging.corp.mongodb.com/3640e8e/node/docsworker-xlarge/DOCSP-11519-mongodb-aws-fixes/fundamentals/authentication)
[Authentication Mechanisms Page](https://docs-mongodbcom-staging.corp.mongodb.com/3640e8e/node/docsworker-xlarge/DOCSP-11519-mongodb-aws-fixes/fundamentals/authentication/mechanisms)
=> DOCSP-11519: fixes to MONGODB-AWS auth presentation

source/index.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-11592
Staging:
=> DOCSP-11592: set mentioned driver version to 3.6

source/usage-examples/findOne.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-11654
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/9c6fa5e/node/docsworker-xlarge/DOCSP-11654-fix-findone/usage-examples/findOne
=> DOCSP-11654: fix findOne usage example

source/fundamentals/monitoring.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-11760
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/356c6fb/node/docsworker-xlarge/DOCSP-11760-clarify-single-instance/fundamentals/monitoring
=> DOCSP-11760: clarify single instance

source/usage-examples/bulkWrite.txt
Staging link: https://docs-mongodborg-staging.corp.mongodb.com/3f7cb30/node/docsworker-xlarge/nathan-contino-mongo-patch-1/
=> Improve vague wording

source/fundamentals/connection.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-12334
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/a276336/node/docsworker-xlarge/DOCSP-12334-alpha-connection-opts/fundamentals/connection#id1
=> DOCSP-12334: alphabetize connection options table

source/fundamentals/connection.txt, source/fundamentals/crud/write-operations/upsert.txt, source/index.txt, source/quick-start.txt
JIRA: 
https://jira.mongodb.org/browse/DOCSP-13620
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/5d040a9/node/docsworker-xlarge/DOCSP-13620-update-syntax-fix/fundamentals/crud/write-operations/upsert
=> DOCSP-13620: fix update syntax

source/usage-examples.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-13901
Missed one instance of "w" parameter.
https://docs-mongodbcom-staging.corp.mongodb.com/9e51727/node/docsworker-xlarge/DOCSP-13901-addendum/usage-examples
=> DOCSP-13901: correct missed update

source/fundamentals/crud/query-document.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-13961
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/be2f69a/node/docsworker-xlarge/DOCSP-13961-evaluation-operators-fix/fundamentals/crud/query-document
=> DOCSP-13961: query operators fixes

source/usage-examples/changeStream.txt
https://jira.mongodb.org/browse/DOCSP-14121
https://docs-mongodbcom-staging.corp.mongodb.com/f0530e6/node/docsworker-xlarge/DOCSP-14121/usage-examples/changeStream
=> DOCSP-14121: remove await on watch()

source/code-snippets/usage-examples/find.js, source/fundamentals/crud/read-operations/cursor.txt, source/usage-examples/find.txt
https://jira.mongodb.org/browse/DOCSP-14153
https://docs-mongodbcom-staging.corp.mongodb.com/806775e/node/docsworker-xlarge/DOCSP-14153-find-feedback-fix/usage-examples/find
=> DOCSP-14153: address feedback on find usage example

source/fundamentals/crud.txt
https://jira.mongodb.org/browse/DOCSP-14015
https://docs-mongodbcom-staging.corp.mongodb.com/5d17454/node/docsworker-xlarge/DOCSP-14015-devhub-links/fundamentals/crud
=> DOCSP-14015: add devhub links

source/quick-start.txt
None
https://docs-mongodbcom-staging.corp.mongodb.com/f862cf2/node/docsworker-xlarge/022321-fix-typo/quick-start/
=> 022321-fix-typo

source/code-snippets/crud/arrayFilters.js, source/code-snippets/crud/startrek.js, source/code-snippets/crud/theaters.js, source/code-snippets/indexes/compound.js, source/code-snippets/indexes/geo.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/code-snippets/indexes/unique.js, source/code-snippets/usage-examples/bulkWrite.js, source/code-snippets/usage-examples/changeStream.js, source/code-snippets/usage-examples/deleteMany.js, source/code-snippets/usage-examples/deleteOne.js, source/code-snippets/usage-examples/distinct.js, source/code-snippets/usage-examples/find.js, source/code-snippets/usage-examples/findOne.js, source/code-snippets/usage-examples/insertMany.js, source/code-snippets/usage-examples/insertOne.js, source/code-snippets/usage-examples/replaceOne.js, source/code-snippets/usage-examples/updateMany.js, source/code-snippets/usage-examples/updateOne.js, source/quick-start.txt
https://jira.mongodb.org/browse/DOCSP-8887
https://docs-mongodbcom-staging.corp.mongodb.com/c55358c/node/docsworker-xlarge/DOCSP-8887-standardize-code-snippets/
=> standardized variable naming in code snippets

source/fundamentals/connection.txt
https://jira.mongodb.org/browse/DOCSP-10662
https://docs-mongodbcom-staging.corp.mongodb.com/4455c90/node/docsworker-xlarge/DOCSP-10662/fundamentals/connection/#connection-options
=> DOCSP 10662

source/fundamentals/connection.txt
https://jira.mongodb.org/browse/DOCSP-10662
https://docs-mongodbcom-staging.corp.mongodb.com/e1cd138/node/docsworker-xlarge/DOCSP-10662-V3.6/fundamentals/connection/#connection-options
=> Docsp 10662 v3.6

config/redirects
@terakilobyte Just what it says on the tin!
=> Update redirects to direct / -> /current

source/faq.txt, source/fundamentals/authentication/mechanisms.txt, source/fundamentals/logging.txt, source/fundamentals/monitoring.txt
https://jira.mongodb.org/browse/DOCSP-15469
https://docs-mongodbcom-staging.corp.mongodb.com/edd2123/node/docsworker-xlarge/DOCSP-15469-ColumnSizing/fundamentals/authentication/mechanisms/
https://docs-mongodbcom-staging.corp.mongodb.com/edd2123/node/docsworker-xlarge/DOCSP-15469-ColumnSizing/fundamentals/logging/
https://docs-mongodbcom-staging.corp.mongodb.com/edd2123/node/docsworker-xlarge/DOCSP-15469-ColumnSizing/fundamentals/monitoring/
https://docs-mongodbcom-staging.corp.mongodb.com/edd2123/node/docsworker-xlarge/DOCSP-15469-ColumnSizing/faq/
=> DOCSP-15469 column sizing

source/fundamentals/connection.txt
https://jira.mongodb.org/browse/DOCSP-15854
https://docs-mongodbcom-staging.corp.mongodb.com/6f73378/node/docsworker-xlarge/DOCSP-15854-ColumnWidths/fundamentals/connection/
=> DOCSP-15854 fixed column widths

source/fundamentals/authentication/mechanisms.txt, source/index.txt, source/whats-new.txt
https://jira.mongodb.org/browse/DOCSP-14426
https://docs-mongodbcom-staging.corp.mongodb.com/bd77764/node/docsworker-xlarge/DOCSP-14426-WhatsNew/whats-new/
=> DOCSP-14426 whats new

source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
https://jira.mongodb.org/browse/DOCSP-15980
https://docs-mongodbcom-staging.corp.mongodb.com/1bde2c2/node/docsworker-xlarge/DOCSP-15980-typoFixes/usage-examples/insertOne/
https://docs-mongodbcom-staging.corp.mongodb.com/1bde2c2/node/docsworker-xlarge/DOCSP-15980-typoFixes/usage-examples/insertMany/
https://docs-mongodbcom-staging.corp.mongodb.com/1bde2c2/node/docsworker-xlarge/DOCSP-15980-typoFixes/usage-examples/updateOne/
https://docs-mongodbcom-staging.corp.mongodb.com/1bde2c2/node/docsworker-xlarge/DOCSP-15980-typoFixes/usage-examples/updateMany/
https://docs-mongodbcom-staging.corp.mongodb.com/1bde2c2/node/docsworker-xlarge/DOCSP-15980-typoFixes/usage-examples/replaceOne/
https://docs-mongodbcom-staging.corp.mongodb.com/1bde2c2/node/docsworker-xlarge/DOCSP-15980-typoFixes/usage-examp …
=> DOCSP-15980  typo fixes

source/fundamentals/crud/write-operations/insert.txt
Current page: https://docs.mongodb.com/drivers/node/current/fundamentals/crud/write-operations/insert/ 
https://jira.mongodb.org/browse/DOCSP-14364
https://docs-mongodbcom-staging.corp.mongodb.com/b712a41/node/docsworker-xlarge/DOCSP-14364-UpdatingCRUDInsert/fundamentals/crud/write-operations/insert/
=> DOCSP-14364 updating CRUDInsert

source/quick-start.txt
This adds a tip admonition about node version and object destructuring assignment
https://jira.mongodb.org/browse/DOCSP-16040
https://docs-mongodbcom-staging.corp.mongodb.com/958be3b/node/docsworker-xlarge/DOCSP-16040/quick-start/
=> Docsp 16040

source/fundamentals/authentication/enterprise-mechanisms.txt, source/fundamentals/connection.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/query-document.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/read-operations/text.txt, source/fundamentals/crud/write-operations/change-a-document.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/embedded-arrays.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/monitoring.txt, source/fundamentals/promises.txt, source/usage-examples.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt
Added a sidebar TOC to pages that didn't have them.
For pages without headings, they will be captured in another ticket along with adding a TOC for them.
https://jira.mongodb.org/browse/DOCSP-16392
https://docs-mongodbcom-staging.corp.mongodb.com/4b6459e/node/docsworker-xlarge/DOCSP-16392-SidebarTOC/fundamentals/authentication/enterprise-mechanisms/
https://docs-mongodbcom-staging.corp.mongodb.com/4b6459e/node/docsworker-xlarge/DOCSP-16392-SidebarTOC/fundamentals/connection/
https://docs-mongodbcom-staging.corp.mongodb.com/4b6459e/node/docsworker-xlarge/DOCSP-16392-SidebarTOC/fundamentals/crud/compound-operations/
https://docs-mongodbcom-staging.corp.mongodb.com/4b6459e/node/docsworker-xlarge/DOCSP-16392-SidebarTOC/fundamentals/crud/query-document/ …
=> DOCSP-16392 sidebar toc

source/faq.txt, source/fundamentals/collations.txt, source/fundamentals/connection.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/logging.txt, source/fundamentals/promises.txt, source/index.txt, source/usage-examples/bulkWrite.txt, source/usage-examples/changeStream.txt, source/usage-examples/command.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt, source/whats-new.txt
Update all links for v4.0 docs
https://jira.mongodb.org/browse/DOCSP-15981
https://docs-mongodborg-staging.corp.mongodb.com/351d6ae/node/docsworker-xlarge/DOCSP-15981-Update-Node-Links/
- Links will not work until snooty-parser has node directive updated
=> Docsp 15981 update node links

source/faq.txt, source/fundamentals/collations.txt, source/fundamentals/connection.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/logging.txt, source/fundamentals/promises.txt, source/index.txt, source/usage-examples/bulkWrite.txt, source/usage-examples/changeStream.txt, source/usage-examples/command.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt, source/whats-new.txt
Updated node-api to v3.6 directive
https://jira.mongodb.org/browse/DOCSP-16370
https://docs-mongodbcom-staging.corp.mongodb.com/33af875/node/docsworker-xlarge/DOCSP-16370-NewDirective/
=> DOCSP-16370 node-api-3.6 directive

source/index.txt
https://jira.mongodb.org/browse/DOCSP-14427
https://docs-mongodbcom-staging.corp.mongodb.com/6b7ec0b/node/docsworker-xlarge/DOCSP-14427-LearnSection/
=> DOCSP-14427 learn section

source/fundamentals/crud/write-operations/insert.txt
https://jira.mongodb.org/browse/DOCSP-16443
https://docs-mongodborg-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-16443-InsertImprovement/fundamentals/crud/write-operations/insert/
=> DOCSP-16443 insert improvement

source/fundamentals/connection.txt, source/includes/localhost-connection.rst, source/quick-start.txt
Added information about connecting to localhost.
https://jira.mongodb.org/browse/DOCSP-16447
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-16447-LocalhostConnection-v3.6/quick-start/#connect-to-localhost
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-16447-LocalhostConnection-v3.6/fundamentals/connection/#connect-to-localhost
=> DOCSP-16447 localhost connection

source/includes/connect-guide-note.rst
https://jira.mongodb.org/browse/DOCSP-17318
Example where the note is included:
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17318-update-connection-guide/usage-examples/findOne/
=> DOCSP-17318: update connection guide

source/usage-examples/changeStream.txt
Fix error error in code snippet found from reader feedback.
https://jira.mongodb.org/browse/DOCSP-17306
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17306-Fix-Change-Streams-Note/usage-examples/changeStream/
=> DOCSP-17306 Fix Change Streams Note

source/whats-new.txt
Added the new features in Node.js v3.7.
https://jira.mongodb.org/browse/DOCSP-17267
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17267-WhatsNew/whats-new/#what-s-new-in-3.7
=> DOCSP-17267 whats new

config/redirects
https://docs-mongodborg-staging.corp.mongodb.com/NNNNNNN/node/docsworker-xlarge/NNNNNNNNNNN/
=> add redirect

source/index.txt
Reordered the sidebar TOC to match our Java docs.
https://jira.mongodb.org/browse/DOCSP-17643
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17643-SidebarOrder/
=> DOCSP-17643 sidebar toc updates

source/code-snippets/authentication/aws.js, source/fundamentals/authentication/mechanisms.txt
https://jira.mongodb.org/browse/DOCSP-13409
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-13409-aws-session-token-auth/fundamentals/authentication/mechanisms/#mongodb-aws
=> DOCSP:13409 aws session token auth

source/fundamentals/aggregation.txt
https://jira.mongodb.org/browse/DOCSP-17943
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17943-list-fix-agg/fundamentals/aggregation/
=> DOCSP 17943: list fix on agg page

source/fundamentals/aggregation.txt
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/list-fix-v3.7/fundamentals/aggregation/
=> list format fix on v3.7

source/fundamentals/aggregation.txt
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/list-fix-v4.0/fundamentals/aggregation/
=> List fix on v4.0

source/code-snippets/usage-examples/insertOne.js, source/code-snippets/usage-examples/insertOne.ts, source/usage-examples/insertOne.txt
Add TypeScript Example to InsertOne Page
https://jira.mongodb.org/browse/DOCSP-15236
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17936-InsertOne-TypeScript-Example/usage-examples/insertOne/
=> Docsp 17936 insert one type script example

source/code-snippets/usage-examples/updateOne.js, source/code-snippets/usage-examples/updateOne.ts, source/usage-examples/updateOne.txt
Add TS Variant for Update One Usage Example
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17936-Update-One-TS/usage-examples/updateOne/
=> (DOCSP-17936) Update One TS

source/code-snippets/usage-examples/distinct.ts, source/usage-examples/distinct.txt
TS Variant for Retrieve Distinct Usage Example
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17936-Retrieve-Distinct/usage-examples/distinct/
=> (DOCSP-17936) Retrieve Distinct TS Example

source/code-snippets/usage-examples/insertMany.ts, source/usage-examples/insertMany.txt
Typescript Insert Many usage Example
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17936-Insert-Many-TS/usage-examples/insertMany/
=> DOCSP-17936 add TS Insert Many usage example

source/code-snippets/usage-examples/find.js, source/code-snippets/usage-examples/find.ts, source/usage-examples/find.txt
Add TS Variant for Find Multiple Usage Example
https://jira.mongodb.org/browse/DOCSP-17963
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17936-Find-Multiple/usage-examples/find/
=> (DOCSP 17936) Find TS

source/code-snippets/usage-examples/deleteMany.js, source/code-snippets/usage-examples/deleteMany.ts, source/usage-examples/deleteMany.txt
TS Variant for Delete Many Usage Example
https://docs-mongodborg-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17936-Delete-Many/usage-examples/deleteMany
=> (DOCSP 17936) Delete Many TS Example

source/code-snippets/usage-examples/updateMany.js, source/code-snippets/usage-examples/updateMany.ts, source/usage-examples/updateMany.txt
Add TS Variant for Update Many Usage Example
http://docs-mongodborg-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17936-Update-Many/usage-examples/updateMany/
=> (DOCSP-17936) Update Many TS Example

source/code-snippets/usage-examples/replaceOne.js, source/code-snippets/usage-examples/replaceOne.ts, source/usage-examples/replaceOne.txt
Add TS Variant for Replace One Usage Example
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17936-Replace-Document/usage-examples/replaceOne/
=> (DOCSP 17936) Replace One TS

source/code-snippets/usage-examples/findOne.ts, source/usage-examples/findOne.txt
Add typescript example for Find One. 
https://jira.mongodb.org/browse/DOCSP-15236
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17936-Find-One/usage-examples/findOne/
=> (DOCSP-17936) FindOne TypeScript example

source/code-snippets/usage-examples/bulkWrite.js, source/code-snippets/usage-examples/bulkWrite.ts, source/usage-examples/bulkWrite.txt
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17936-Bulk-TS/usage-examples/bulkWrite/
=> (DOCSP-17936) Bulk TS Example

snooty.toml, source/fundamentals.txt, source/fundamentals/aggregation.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/time-series.txt
Fundamentals > Time Series
https://jira.mongodb.org/browse/DOCSP-17733
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17733-Time-Series/fundamentals/time-series/
=> (DOCSP-17733) Time Series 

source/quick-start.txt
Added the option to download the project instead of manually creating it.
https://jira.mongodb.org/browse/DOCSP-13650
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=614a5aefbc80a0834b3d6a3c
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-13650-addingDownloadableProj/quick-start
=> DOCSP-13650 added downloadable project

source/fundamentals/connection.txt, source/whats-new.txt
https://jira.mongodb.org/browse/DOCSP-19604
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=618d4119c13055282d26ad2b
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-19604-srv-options/fundamentals/connection/#connection-options
=> DOCSP-19604: mongoclient srv options

snooty.toml
This is in preparation for the 4.2 branch cut.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6195608a5314b0809f5bb8a7
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/cut-4.2/
=> bump to 4.2 for api docs

source/index.txt
https://jira.mongodb.org/browse/DOCSP-20494
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61f022e0bcf82347e5c58c01
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-20494/
=> (DOCSP-20494) standardize driver intros: node.js

source/fundamentals.txt, source/fundamentals/csfle.txt, source/includes/fundamentals-sections.rst
**For copy review:**
In the Example section, I link out to [this University GitHub example](https://github.com/mongodb-university/csfle-guides/tree/master/nodejs) rather than creating my own. In the Java driver CSFLE docs, Ross put together a [Java tour](https://github.com/mongodb/mongo-java-driver/tree/master/driver-sync/src/examples/tour) (here are the [examples in the Java driver docs](https://docs.mongodb.com/drivers/java/sync/current/fundamentals/csfle/#examples)). Do you think the University GitHub is enough, or should I find/create examples closer to Ross' tour here?
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=620ab93a382d7fe4ee04f393
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge …
=> (DOCSP-18745) Node CSFLE fundementals

source/fundamentals.txt, source/fundamentals/csfle.txt, source/includes/fundamentals-sections.rst
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=620ff2299c4c7f6bfb975c4c
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18745-backport-v4.3/
=> Docsp 18745 backport v4.3

source/fundamentals.txt, source/fundamentals/csfle.txt, source/includes/fundamentals-sections.rst
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=620fffc19c4c7f6bfb9a8475
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18745-backport-v4.2/
=> Backport DOCSP-18745 to v4.2

source/fundamentals.txt, source/fundamentals/csfle.txt, source/includes/fundamentals-sections.rst
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=621002039c4c7f6bfb9b031c
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18745-backport-v4.1/
=> merge DOCSP-18745

source/fundamentals.txt, source/fundamentals/csfle.txt, source/includes/fundamentals-sections.rst
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=621004ac9c4c7f6bfb9b9236
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18745-backport-v4.0/
=> Backport DOCSP-18745

source/quick-start.txt
n/a
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=621d48669c4c7f6bfb4db668
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/add-ref/quick-start/
=> add ref to node quickstart

.github/pull_request_template.md, REVIEWING.md
Add reviewer guidelines to PR template.
Note: the verbiage in REVIEWING.md was already approved by the team.
=> Add reviewer guidelines

source/fundamentals/promises.txt
N/A
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6227a45f1a622fb274543fae
N/A
=> add ref for guides

source/fundamentals/crud/write-operations/embedded-arrays.txt
Updated the CRUD > Write Operations > Update Arrays page.
I know the ticket didn't say to update the entire page, but I thought it could use an improvement in terms of wording.
I'll make a PR to each versioned branch after this gets approved.
https://jira.mongodb.org/browse/DOCSP-20598
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=623b62680ab54725f1946e6a
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-20598-Dot-Notation/fundamentals/crud/write-operations/embedded-arrays/
=> updated update arrays page

source/whats-new.txt
https://jira.mongodb.org/browse/DOCSP-21435
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=623db8130ab54725f1159866
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-21435-whats-new-3.7/whats-new/
=> DOCSP-21435: Apply what's new for 3.7

source/code-snippets/quick-reference.js, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/geo.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/read-operations/project.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/read-operations/skip.txt, source/fundamentals/crud/read-operations/sort.txt, source/fundamentals/crud/read-operations/text.txt, source/fundamentals/crud/write-operations/change-a-document.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/embedded-arrays.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/indexes.txt, source/index.txt, source/quick-reference.txt, source/usage-examples/bulkWrite.txt, source/usage-examples/changeStream.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
https://jira.mongodb.org/browse/DOCSP-21519
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=624ded910fdfea9c37ff2e74
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-21519-node-tldr/quick-reference/
=> DOCSP-21519: node TLDR

snooty.toml, source/code-snippets/quick-reference.js, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/geo.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/read-operations/project.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/read-operations/skip.txt, source/fundamentals/crud/read-operations/sort.txt, source/fundamentals/crud/read-operations/text.txt, source/fundamentals/crud/write-operations/change-a-document.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/embedded-arrays.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/indexes.txt, source/index.txt, source/quick-reference.txt, source/usage-examples/bulkWrite.txt, source/usage-examples/changeStream.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
https://jira.mongodb.org/browse/DOCSP-21877
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=624f582c0fdfea9c374a5d92
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-21877-tldr-4.0/quick-reference/
=> DOCSP-21877 tldr 4.0

snooty.toml, source/code-snippets/quick-reference.js, source/fundamentals/crud/read-operations/cursor.txt, source/fundamentals/crud/read-operations/geo.txt, source/fundamentals/crud/read-operations/limit.txt, source/fundamentals/crud/read-operations/project.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/read-operations/skip.txt, source/fundamentals/crud/read-operations/sort.txt, source/fundamentals/crud/read-operations/text.txt, source/fundamentals/crud/write-operations/change-a-document.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/embedded-arrays.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/indexes.txt, source/index.txt, source/quick-reference.txt, source/usage-examples/bulkWrite.txt, source/usage-examples/changeStream.txt, source/usage-examples/count.txt, source/usage-examples/deleteMany.txt, source/usage-examples/deleteOne.txt, source/usage-examples/distinct.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertMany.txt, source/usage-examples/insertOne.txt, source/usage-examples/replaceOne.txt, source/usage-examples/updateMany.txt, source/usage-examples/updateOne.txt
https://jira.mongodb.org/browse/DOCSP-21875
- Changes for 3.6 will include snooty.toml version source constant, but should be otherwise suitable for applying a cherry-pick.
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=624f5fc70fdfea9c374c0707
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-21875-quick-reference/quick-reference/
=> DOCSP-21519: node TLDR 3.x

.github/pull_request_template.md, README.rst
Updates to README and PR template
=> community updates

config/redirects, snooty.toml, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-22648>
Staging - [Quick Start ](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-22648-node-v4.6/quick-start/)
=> DOCSP-22648: Node v4.6 release

source/fundamentals/typescript.txt
Adding section on working with _id in TypeScript
JIRA - <https://jira.mongodb.org/browse/DOCSP-20024>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-20024//>
=> DOCSP-20024 Added section on working with id field

source/whats-new.txt
Updated the What's New section in v4.6 based off of [the engineers release notes](https://github.com/mongodb/node-mongodb-native/releases/tag/v4.6.0).
JIRA - <https://jira.mongodb.org/browse/DOCSP-22708>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-22708-v4.6WhatsNew/whats-new/#what-s-new-in-4.6>
=> DOCSP-22708 whats new v4.6

source/whats-new.txt
Add [4.7 Release Notes](https://github.com/mongodb/node-mongodb-native/blob/main/HISTORY.md#470-2022-06-06) to whats new page.
JIRA - <https://jira.mongodb.org/browse/DOCSP-23150>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-23150-Node-4.7-Release-Notes/whats-new/#std-label-version-4.7)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62a0fab77cf5397525c5a2b7)
=> DOCSP-23150 4.7 Release Notes

source/quick-start.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-23259>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-23259-atlas-cli-setup/quick-start/>
=> DOCSP-23259: update atlas instructions

snooty.toml, source/fundamentals/indexes.txt
Added a section about clustered indexes on the index page.
JIRA - <https://jira.mongodb.org/browse/DOCSP-22868>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-22868/fundamentals/indexes/#clustered-indexes>
=> DOCSP-22868 clustered indexes

source/fundamentals/connection/connection-options.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-22852>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-22852-maxConnecting-option/fundamentals/connection/connection-options/>
=> DOCSP-22852: Added maxConnecting info

source/fundamentals/connection/connection-options.txt
(cherry picked from commit d6c9ccc96d6af388d742f76c8b7d8fdee4983d73)
JIRA - <https://jira.mongodb.org/browse/DOCSP-22852>
=> DOCSP-22852: Added maxConnecting info (#336)

source/fundamentals/collations.txt, source/fundamentals/crud/query-document.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/distinct.txt, source/usage-examples/distinct.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-18223>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18223-distinct-values-page/fundamentals/crud/read-operations/distinct/>
=> DOCSP-18223: added a distinct() page

source/fundamentals/crud.txt, source/quick-start.txt, source/usage-examples.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-23560>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-23560-quickstart-fixes/quick-start/>
=> DOCSP-23560: quickstart fixes

source/fundamentals/typescript.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-23583>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-23583/fundamentals/typescript/
=> remove editorializing

source/fundamentals/typescript.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-23583
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-23583/fundamentals/typescript/
=> Backport docsp-23583 to v4.1

source/fundamentals/typescript.txt
* remove editorializing
* autobuilder'
* remove informal language
Co-authored-by: Nathan Leniz <nathan.leniz@mongodb.com>
JIRA - https://jira.mongodb.org/browse/DOCSP-23583
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-23583/fundamentals/typescript/
=> Backport docsp-23583 to v4.0

source/fundamentals/collations.txt, source/fundamentals/connection/connection-options.txt, source/fundamentals/crud/query-document.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/read-operations/distinct.txt, source/usage-examples/distinct.txt
* DOCSP-18223: added a distinct() page
* DOCSP-18223: update TOC
* better example documents
* fixed rst mistakes
* fixed wording
* small wording fix
* another small wording fix
JIRA - <https://jira.mongodb.org/browse/DOCSP-18223>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.7/>
=> DOCSP-18223: added a distinct() page (#338)

source/usage-examples/distinct.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-23615-fixing-links/usage-examples/distinct/>
=> DOCSP-23615: updating links

source/usage-examples/distinct.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v3.6/>
=> DOCSP-23615: updating links (#358) v3.6

source/usage-examples/distinct.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v3.7/>
=> DOCSP-23615: updating links (#358) v3.7

source/usage-examples/distinct.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.1/>
=> DOCSP-23615: updating links (#358) v4.1

source/usage-examples/distinct.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.2/>
=> DOCSP-23615: updating links (#358) v4.2

source/usage-examples/distinct.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.3/>
=> DOCSP-23615: updating links (#358) v4.3

source/usage-examples/distinct.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.4/>
=> DOCSP-23615: updating links (#358) v4.4

source/usage-examples/distinct.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.5/>
=> DOCSP-23615: updating links (#358) v4.5

source/usage-examples/distinct.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/v4.6/>
=> DOCSP-23615: updating links (#358) v4.6

source/usage-examples/distinct.txt
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.7/>
=> DOCSP-23615: updating links (#358) v4.7

.github/workflows/check-autobuilder.yml
Adds [snooty-autobuilder-check](https://github.com/cbush/snooty-autobuilder-check)
JIRA - None
Staging - None
=> Snooty Autobuilder Check Action

source/fundamentals/encrypt-fields.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-24285)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.8/fundamentals/encrypt-fields/)
=> Backport - Updating QE/CSFLE links to refs

source/fundamentals/crud.txt
=> 081622: remove broken link (#392) for v4.4

source/fundamentals/crud.txt, source/fundamentals/promises.txt
=> 081622: remove broken link (#392) for v4.0

source/fundamentals/crud.txt
=> 081622: remove broken link (#392) for v4.7

source/fundamentals/crud.txt
=> 081622: remove broken link (#392) for v4.8

source/fundamentals/crud.txt
=> 081622: remove broken link (#392) for v4.5

source/fundamentals/crud.txt, source/fundamentals/promises.txt
=> 081622: remove broken link (#392) for v4.1

source/fundamentals/crud.txt, source/fundamentals/promises.txt
=> 081622: remove broken link (#392) for v3.6

source/fundamentals/crud.txt, source/fundamentals/promises.txt
=> 081622: remove broken link (#392) for v4.3

source/fundamentals/crud.txt, source/fundamentals/promises.txt
=> 081622: remove broken link (#392) for v3.7

source/fundamentals/crud.txt, source/fundamentals/promises.txt
=> 081622: remove broken link (#392) for v4.2

source/compatibility.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-24481
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v3.6/compatibility/
=> [DOCSP-24481] V4.8 backport (#389)

.github/workflows/copy-compat-to-docs-shared.yml
Attempting to expose env to all jobs.
=> make env available to all jobs

source/includes/language-compatibility-table-node.rst, source/includes/mongodb-compatibility-table-node.rst
=> one blank line at end of file

.github/workflows/copy-compat-to-docs-shared.yml, source/includes/language-compatibility-table-node.rst, source/includes/mongodb-compatibility-table-node.rst
=> workflow testing

source/includes/language-compatibility-table-node.rst, source/includes/mongodb-compatibility-table-node.rst
=> remove testing comment

source/code-snippets/quick-reference.js, source/quick-reference.txt
This removes unnecessary awaits from the quick reference.
JIRA - <https://jira.mongodb.org/browse/DOCSP-23737>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-23737/quick-reference/>
=> consistent await in quick reference

source/quick-start.txt
I will archive the repo after LGTM.
JIRA - <https://jira.mongodb.org/browse/DOCSP-24384>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-24384/quick-start/>
=> Docsp 24384

source/faq.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-21804>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-21804/faq/>
=> add ipv6 info to faq

source/code-snippets/quick-reference.js, source/faq.txt, source/fundamentals/authentication.txt, source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection/connection-options.txt, source/quick-reference.txt, source/quick-start.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/backport-to-4.8/)
=> Backport to 4.8

source/code-snippets/quick-reference.js, source/faq.txt, source/fundamentals/authentication.txt, source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection/connection-options.txt, source/quick-reference.txt, source/quick-start.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/backport-to-4.7/)
=> Backport to 4.7

snooty.toml, source/code-snippets/quick-reference.js, source/faq.txt, source/fundamentals/authentication.txt, source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection/connection-options.txt, source/quick-reference.txt, source/quick-start.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/backport-to-4.6/)
=> Backport to 4.6

source/code-snippets/quick-reference.js, source/faq.txt, source/fundamentals/authentication.txt, source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection/connection-options.txt, source/quick-reference.txt, source/quick-start.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/backport-to-4.5/)
=> Backport to 4.5

source/code-snippets/quick-reference.js, source/faq.txt, source/fundamentals/authentication.txt, source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection/connection-options.txt, source/quick-reference.txt, source/quick-start.txt
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/node/docsworker-xlarge/backport-to-4.4/)
=> Backport to 4.4

source/code-snippets/quick-reference.js, source/faq.txt, source/fundamentals/authentication.txt, source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection/connection-options.txt, source/quick-reference.txt, source/quick-start.txt
=> Backport to 4.3

source/code-snippets/quick-reference.js, source/faq.txt, source/fundamentals/authentication.txt, source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection/connection-options.txt, source/quick-reference.txt, source/quick-start.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/backport-to-4.2/)
=> Backport to 4.2

source/fundamentals/authentication.txt, source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection/connection-options.txt
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/backport-to-4.0/
=> Backport to 4.0

source/fundamentals/authentication.txt, source/fundamentals/authentication/mechanisms.txt, source/fundamentals/connection/connection-options.txt
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/node/docsworker-xlarge/backport-to-4.1/)
=> Backport to 4.1

source/fundamentals/connection/connection-options.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/link-fix/fundamentals/connection/connection-options/
=> fix broken link

source/fundamentals/connection/connection-options.txt
(cherry picked from commit c6341672bbfa82dd9606a187960a9015dc8efd1d)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.9/fundamentals/connection/connection-options/
=> fix broken link (#437)

config/redirects, source/fundamentals/connection.txt, source/fundamentals/connection/lambda.txt
This adds a container page and a redirect to send users to the appropriate Atlas page. The redirect can't be tested until it is deployed.
[JIRA](https://jira.mongodb.org/browse/DOCSP-23022)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-23022/fundamentals/connection/lambda/)
=> Docsp 23022

source/usage-examples/command.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/100522-fix-link/usage-examples/command/
=> 100522-fix-mongosh-link

config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-26110
**no staging because redirects will only work after merging and deploying**
=> DOCSP-26110: symlink for redirects

config/redirects, source/fundamentals/connection.txt, source/fundamentals/connection/lambda.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-26110-symlink/fundamentals/connection/
**And check redirect from left hand tree under Connection tab**
=> AWS lambda redirect

source/whats-new.txt
[4.12.1 Release Notes](https://github.com/mongodb/node-mongodb-native/releases)
JIRA - https://jira.mongodb.org/browse/DOCSP-26701
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-26701-version/whats-new/
=> [DOCSP-26701] Add 4.12.1 admonition

source/code-snippets/transactions/txn-callback.js, source/code-snippets/transactions/txn-core.js, source/fundamentals/crud/write-operations/pkFactory.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26162
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-26162-mongoclient/fundamentals/
=> [docsp-26162] Remove unsupported options

source/faq.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26186
Staging - [FAQ 1](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-26186-maxtimeMS-explanation/faq/#what-is-the-difference-between--connecttimeoutms----sockettimeoutms--and--maxtimems--) // [FAQ 2](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-26186-maxtimeMS-explanation/faq/#how-can-i-prevent-long-running-operations-from-slowing-down-the-server-)
=> DOCSP-26186: maxTimeMS explanation

source/code-snippets/authentication/aws-env-variable.js, source/fundamentals/authentication/mechanisms.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-25547>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-25547-clarify-aws-admonition/fundamentals/authentication/mechanisms/#mongodb-aws
=> DOCSP-25547-clarify-aws-auth

source/fundamentals/typescript.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26238
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-26238-key-from-variable/fundamentals/typescript/#referencing-keys-that-incorporate-variables
=> DOCSP-26238: create keys from variables

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25706
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-25706-electionId-prioritzation/whats-new/#what-s-new-in-4.11
=> DOCSP-25706: electionid prioritization

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27170
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-27170-aws-optional/whats-new/#what-s-new-in-5.0
includes a revision suggested in [this comment](https://github.com/mongodb/docs-node/pull/489#discussion_r1084243703).
=> DOCSP-27170: aws sdk is an optional dependency

source/quick-start.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27530
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.1/quick-start/
=> docsp-27530 - remove cloning quick-start option

source/index.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/link-fixes/
=> update m220js link

config/redirects, snooty.toml
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v5-upgrade/quick-start/
=> Update to v5.0

source/whats-new.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/consolidate-breaking-changes-5.0/whats-new/
=> consolidate breaking changes for 5.0

source/whats-new.txt
JIRA - None
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/020823-whatsnew-link-fix/whats-new/
=> Fix v4.14 link in what's new

source/code-snippets/connection/connect.js, source/fundamentals/connection/connect.txt, source/fundamentals/connection/connection-options.txt, source/includes/localhost-connection.rst, source/quick-start.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-18071
Staging
[Connection Guide](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18071-fix-conn-guide/fundamentals/connection/connect/)
[Connection Options](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-18071-fix-conn-guide/fundamentals/connection/connection-options/)
=> DOCSP-18071: fix connection guide

source/code-snippets/monitoring/cpm-subscribe.js, source/fundamentals/monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27849
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-27849-connection-monitoring/fundamentals/monitoring/connection-monitoring/#event-descriptions
=> Docsp 27849 connection monitoring

source/code-snippets/indexes/compound.js, source/code-snippets/indexes/multikey.js, source/code-snippets/indexes/single-field.js, source/code-snippets/indexes/text.js, source/fundamentals/indexes.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-14352
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-14352-multikey-indexes/fundamentals/indexes/#multikey-indexes--indexes-on-array-fields-
=> DOCSP-14352: fix multikey index description & example

source/fundamentals/logging.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28100
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-28100-monitoring-link/fundamentals/logging/
=> docsp-28100 - connection monitoring link

source/fundamentals/connection/connection-options.txt, source/index.txt, source/whats-new.txt
Removed references to OCSP per convo with Neal B.
JIRA - https://jira.mongodb.org/browse/DOCSP-12262
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-12262-remove-ocsp/
=> docsp-12262 - remove OCSP

source/fundamentals/connection/connection-options.txt, source/fundamentals/crud/query-document.txt, source/fundamentals/crud/read-operations/text.txt, source/fundamentals/indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-28396>
Staging -
- https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-28396/fundamentals/connection/connection-options/
- https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-28396/fundamentals/crud/query-document/
- https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-28396/fundamentals/crud/read-operations/text/
- https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-28396/fundamentals/indexes/
=> DOCSP-28396: Removed instances of e.g.

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27923
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-27923-stable-api/fundamentals/connection/connect/
=> add stableapi connection example

source/code-snippets/connection/stable-api-connect.js, source/fundamentals/connection/connect.txt
(cherry picked from commit d1792179c61c0d3601f59c94f7f99e6cd4962069)
Staging -https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.6/fundamentals/connection/connect/
=> Backport - add stableapi connection example (#590)

source/usage-examples/count.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27257
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-27257-countDocuments-collscan/usage-examples/count/
=> DOCSP-27257 Add tip to avoid collScan on countDocuments

source/code-snippets/connection/stable-api-connect.js
JIRA - [DOCSP-27923](https://jira.mongodb.org/browse/DOCSP-27923)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/stable-api-updates-cleanup/fundamentals/connection/connect/#atlas-connection-example
=> match conventions

source/fundamentals/authentication/mechanisms.txt
The existing page format made it challenging to fit this information in. Rather than rewrite the whole section, I preserved as much of the old format and content as possible while making the changes I thought were necessary to accommodate EKS auth.
[C# Auth docs for reference.](https://www.mongodb.com/docs/drivers/csharp/current/fundamentals/authentication/#std-label-csharp-mongodb-aws)
JIRA - https://jira.mongodb.org/browse/DOCSP-28762
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/docsp-28762-aws-eks/fundamentals/authentication/mechanisms/#mongodb-aws
=> docsp-28762 - add aws eks authentication

source/fundamentals/authentication/enterprise-mechanisms.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28231
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-28231-canon-hostames-kerb/fundamentals/authentication/enterprise-mechanisms/#kerberos--gssapi-sspi-)
- [n/a] Are all the links working?
=> DOCSP-28231: hostname canonicalization options for kerberos

source/fundamentals/authentication/mechanisms.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28951
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-28951-credential-providers/fundamentals/authentication/mechanisms/#mongodb-aws) - changes are in "Web Identity Token File" tab.
=> DOCSP-28951 credential providers dependency

config/redirects, snooty.toml, source/whats-new.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v4.15/
=> v4.15 release

source/fundamentals/typescript.txt
(cherry picked from commit a4984732baf24a4b7134bc7f13449205536be613)
=> DOCSP-28958 Clarify Typescript Find and the _id section (#644)

.backportrc.json
=> update backport file

config/redirects, snooty.toml, source/fundamentals.txt, source/fundamentals/bson.txt, source/fundamentals/bson/undefined-values.txt, source/fundamentals/bson/utf8-validation.txt, source/fundamentals/crud/write-operations/upsert.txt, source/includes/fundamentals-sections.rst
Merge conflicts in redirect file
=> backport #674 to v5.0

source/code-snippets/crud/arrayFilters.js, source/fundamentals/crud/write-operations/embedded-arrays.txt
JIRA - [DOCSP-29418](https://jira.mongodb.org/browse/DOCSP-29418)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-29418-improve-array-updates-pg/fundamentals/crud/write-operations/embedded-arrays/)
=> DOCSP-29418: improve array updates pg

source/compatibility.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/use-sharedinclude/compatibility/
APPLIES TO ALL NUMBERED VERSIONS
=> replace include with sharedinclude

source/usage-examples/find.txt
Co-authored-by: Caitlin Davey <caitlin.davey@mongodb.com>
(cherry picked from commit bdb82b9ec536602b04311a511cc9f021098a7ad4)
JIRA - <https://jira.mongodb.org/browse/DOCSP-30081>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v5.5/>
=> Cherry Picked

source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30318>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-30318-driver-5.6.0-release/compatibility/
=> DOCSP-30318: v5.6 shared compat tables

source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31193>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31193-shared-compat-tables/compatibility/
=> DOCSP-31193: v5.7 shared compatibility tables

source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30326>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-30326-fix-broken-link/>
=> Fixed broken link on index page

source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30326>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v3.7/>
=> DOCSP-30081: Fix find to find()

source/fundamentals/gridfs.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31268>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31268-add-missing-bracket/fundamentals/gridfs/#upload-files>
=> DOCSP-31268: Added missing bracket to code sample

source/fundamentals/gridfs.txt
(cherry picked from commit d989545c3cb8a8b999cd122cf3177f19525600d3)
JIRA - <https://jira.mongodb.org/browse/DOCSP-31268>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/v5.7>
=> DOCSP-31268: Added missing bracket to code sample (#714)

source/compatibility.txt, source/includes/component-compatibility-table-node.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-32228>
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32228-component-support-matrix/compatibility/#component-compatibility
=> DOCSP-32228: Add component support matrix

snooty.toml, source/index.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-32417>
Staging:
- [What's New](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32417-v4.17-branch/whats-new/#std-label-version-4.17)
- [Reference to the version](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32417-v4.17-branch/quick-start/#add-mongodb-as-a-dependency)
=> DOCSP-32417-v4.17-branch

source/upgrade.txt, source/whats-new.txt
JIRA - 
https://jira.mongodb.org/browse/DOCSP-31649
https://jira.mongodb.org/browse/DOCSP-31740
https://jira.mongodb.org/browse/DOCSP-32050
https://jira.mongodb.org/browse/DOCSP-31739
https://jira.mongodb.org/browse/DOCSP-31645
Staging - 
[Upgrade Driver Versions](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31739-remove-strings-objectid/upgrade/#version-6.x-breaking-changes)
[What's New](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31739-remove-strings-objectid/whats-new/#std-label-version-6.0)
=> Various v6 breaking changes

source/code-snippets/stable-api/basic.js
https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-32718-stableapi-basic-comments/fundamentals/stable-api/#enable-the-stable-api-on-a-mongodb-client
=> DOCSP-32718: stableapi basic UE code comments

source/code-snippets/stable-api/options.js
https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-32718-stableapi-options-comments/fundamentals/stable-api/#stable-api-options
=> DOCSP-32718: stableapi options code comments

source/code-snippets/indexes/multikey.js
https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-32718-multikey-comments/fundamentals/indexes/#multikey-indexes--indexes-on-array-fields-
=> DOCSP-32718: multikey code comments

source/code-snippets/crud/runCommand.js
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-32718-runCommand-comments/fundamentals/run-command/>
=> DOCSP-32718: runCommand comments

config/redirects, source/fundamentals/crud/write-operations.txt, source/fundamentals/crud/write-operations/delete.txt, source/fundamentals/crud/write-operations/modify.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31824>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31824-update-titles/fundamentals/crud/write-operations/modify/>
<https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31824-update-titles/fundamentals/crud/write-operations/delete/>
Redirects -
Redirect 301 /docs/drivers/node/v3.6/fundamentals/crud/write-operations/change-a-document/ https://www.mongodb.com/docs/drivers/node/v3.6/fundamentals/crud/write-operations/modify/
Redirect 301 /docs/drivers/node/v3.7/fundamentals/crud/write-operations/change-a-document/ https://www.mongodb.com/docs/drivers/node/v3.7/fundamentals/crud/write-operati …
=> DOCSP-31824: Update page titles

.github/workflows/vale-tdbx.yml
Fix the trigger for the Vale GH action
=> Fix the trigger for the Vale GH action

source/facets.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-32483>
Hi @mongoKart - here's the facet.toml file for the node repo.  Please merge if everything looks good!
Thanks,
Sarah
=> DOCSP-32483 programmatic tagging script for the node repo

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6504806c24fcc731b47db524)
=> Backports DOCSP-32271 to v4.8

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047fd424fcc731b47d83e9)
=> Backports DOCSP-32271 to v4.9

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047f8524fcc731b47d5374)
=> Backports DOCSP-32271 to v4.10

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047f0124fcc731b47d12ed)
=> Backports DOCSP-32271 to v4.11

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047eab24fcc731b47cfaa5)
=> Backports DOCSP-32271 to v4.12

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047e5b24fcc731b47cce33)
=> Backports DOCSP-32271 to v4.13

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047dca24fcc731b47ca407)
=> Backports DOCSP-32271 to v4.14

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047d5424fcc731b47c852b)
=> Backports DOCSP-32271 to v4.15

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047ce724fcc731b47c65ab)
=> Backports DOCSP-32271 to v4.16

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
Backports #718 
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047ca024fcc731b47c35e3)
=> Backports DOCSP-32271 to v4.17

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047c4724fcc731b47c1c51)
=> Backports DOCSP-32271 to v5.0

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047ab124fcc731b47a57bf)
=> Backports DOCSP-32271 to v5.2

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65047a1524fcc731b47a233b)
=> Backports DOCSP-32271 to v5.3

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650479e024fcc731b47a12d7)
=> Backports DOCSP-32271 to v5.4

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650479ab24fcc731b479ec8f)
=> Backports DOCSP-32271 to v5.5

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=650478c024fcc731b47944a8)
=> Backports DOCSP-32271 to v5.7

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6504782924fcc731b479061d)
=> Backports DOCSP-32271 to v5.8

source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/includes/fact-atlas-compatible.rst, source/includes/fact-atlas-link.rst, source/includes/fact-environments.rst, source/index.txt, source/quick-reference.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6504774d24fcc731b478a1c1)
=> Backports DOCSP-32271 to v6.0

source/compatibility.txt, source/includes/lifecycle-schedule-callout.rst
Note: there are a number of facet-related warnings, but they are not expected to impact the publishing process.
Note: Docs Platform mentioned this is an internal build issue that we can safely ignore.
JIRA - <https://jira.mongodb.org/browse/DOCSP-30911>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/node/DOCSP-30911-server-support/compatibility/#mongodb-compatibility
=> DOCSP-30911: Add server lifecycle support callout

source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/update-and-replace-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-24434>
Staging - 
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-24434-meta/usage-examples/find-operations/
=> DOCSP-24434: Add meta descriptions

config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-33066>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/node/DOCSP-33066-SOCKS5-redirects/fundamentals/connection/socks/>
Redirects - 
Redirect 301 /docs/drivers/node/v3.6/fundamentals/connection/socks/ https://www.mongodb.com/docs/drivers/node/v3.6/
Redirect 301 /docs/drivers/node/v3.7/fundamentals/connection/socks/ https://www.mongodb.com/docs/drivers/node/v3.7/
Redirect 301 /docs/drivers/node/v4.0/fundamentals/connection/socks/ https://www.mongodb.com/docs/drivers/node/v4.0/
Redirect 301 /docs/drivers/node/v4.1/fundamentals/connection/socks/ https://www.mongodb.com/docs/drivers/node/v4.1/
Redirect 301 …
=> DOCSP-33066: SOCKS5 Redirects

source/fundamentals/connection/connection-options.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33944>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/node/DOCSP-33944-connection-options-appname/fundamentals/connection/connection-options/#connection-options
Note: not addressing Vale errors in this fix.
=> DOCSP-33944: rename appName connection option

source/usage-examples/deleteOne.txt
JIRA - None
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/node/110623-fix-typo/usage-examples/deleteOne/
=> Remove stray period

source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/crud/write-operations/modify.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-29461>
Staging:
[retrieve data page](https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-29461-node-lab-embedding/fundamentals/crud/read-operations/retrieve/)
[insert page](https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-29461-node-lab-embedding/fundamentals/crud/write-operations/insert/)
[modify documents page](https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-29461-node-lab-embedding/fundamentals/crud/write-operations/modify/)
=> DOCSP-29461: node lab embedding

source/fundamentals/connection/connect.txt, source/fundamentals/encrypt-fields.txt, source/fundamentals/gridfs.txt, source/fundamentals/indexes.txt
Updates from our taxonomy tagging session today.
JIRA - None
=> 110823: taxonomy tagging

.github/pull_request_template.md
=> 110823: Add facets and meta tags to PR template

source/fundamentals/logging.txt
=> Add taxonomy tags to the Logging page

source/fundamentals/crud.txt, source/fundamentals/logging.txt, source/fundamentals/monitoring.txt, source/fundamentals/transactions.txt, source/usage-examples/command.txt, source/whats-new.txt
=> Taxonomy tags

snooty.toml, source/aggregation-tutorials.txt, source/aggregation-tutorials/multi-field-join.txt, source/aggregation-tutorials/one-to-one-join.txt, source/includes/aggregation/one-to-one-join.js, source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-33630
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/node/DOCSP-33630-agg-one-to-one/aggregation-tutorials/one-to-one-join/
=> DOCSP-33630 one-to-one aggregation tutorial

source/quick-start/facets.toml, source/usage-examples/facets.toml
Hey @ccho-mongodb - here's the updated facet.toml files for docs-node.  There weren't any errors on the build log.  Please merge if everything looks good to you!
JIRA - <https://jira.mongodb.org/browse/DOCSP-31343>
Staging - <https://preview-mongodbsarahemlin.gatsbyjs.io/node/DOCSP-31343/>
=> DOCSP-31343 add facet.toml files

source/connection-troubleshooting.txt, source/faq.txt, source/fundamentals/connection/connection-options.txt, source/fundamentals/connection/tls.txt, source/fundamentals/crud/compound-operations.txt, source/fundamentals/crud/read-operations/geo.txt, source/fundamentals/crud/read-operations/project.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/crud/write-operations/upsert.txt, source/fundamentals/monitoring/cluster-monitoring.txt, source/fundamentals/monitoring/command-monitoring.txt, source/fundamentals/monitoring/connection-monitoring.txt, source/fundamentals/promises.txt, source/fundamentals/stable-api.txt, source/fundamentals/typescript.txt, source/includes/localhost-connection.rst, source/index.txt, source/upgrade.txt, source/usage-examples/find.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33948>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/node/DOCSP-33948-atomic-typos/>
=> DOCSP-33948: Atomic typos and cleanup

source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34576>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/node/DOCSP-34576-landing-page-fixes/>
=> DOCSP-34576: Landing page style fixes

source/aggregation-tutorials.txt, source/aggregation-tutorials/one-to-one-join.txt, source/fundamentals/aggregation.txt, source/includes/aggregation/one-to-one-join.js, source/includes/aggregation/template-app.js, source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34038>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-34038-tutorials-landing/aggregation-tutorials/
=> DOCSP-34038: agg tutorials landing

source/aggregation-tutorials.txt, source/aggregation-tutorials/filtered-subset.txt, source/fundamentals/crud/read-operations.txt, source/includes/aggregation/filtered-subset.js
JIRA - https://jira.mongodb.org/browse/DOCSP-33632
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/node/DOCSP-33632-filtered-top-subset/aggregation-tutorials/filtered-subset/
=> DOCSP-33632 Filtered Subset

source/aggregation-tutorials.txt, source/aggregation-tutorials/group-total.txt, source/includes/aggregation/filtered-subset.js, source/includes/aggregation/group-total.js, source/includes/aggregation/multi-field-join.js, source/includes/aggregation/one-to-one-join.js, source/includes/aggregation/template-app.js
JIRA - <https://jira.mongodb.org/browse/DOCSP-33633>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-33633-group-total/aggregation-tutorials/group-total/
=> DOCSP-33633: group total tutorial

source/whats-new.txt
Nothing to preview; this is a preventative measure to avoid build errors when you cross-link to the What's New page.
JIRA - None
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/node/121123-test/
=> 121123 Fix association between title anchor and title in What's New

source/aggregation-tutorials.txt, source/aggregation-tutorials/unpack-arrays.txt, source/includes/aggregation/unpack-arrays.js
JIRA - <https://jira.mongodb.org/browse/DOCSP-34718>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-34718-unpack-arrats/aggregation-tutorials/unpack-arrays/
=> DOCSP-34718: unpack arrays tutorial

source/aggregation-tutorials.txt, source/aggregation-tutorials/filtered-subset.txt, source/aggregation-tutorials/group-total.txt, source/aggregation-tutorials/multi-field-join.txt, source/aggregation-tutorials/one-to-one-join.txt, source/aggregation-tutorials/unpack-arrays.txt, source/includes/aggregation/filtered-subset.js, source/includes/aggregation/multi-field-join.js, source/includes/aggregation/one-to-one-join.js, source/includes/aggregation/template-app.js
JIRA - <https://jira.mongodb.org/browse/DOCSP-34717>
**Staging:**
- [Landing page](https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-34717-agg-tut-cleanup/aggregation-tutorials/)
- [Filtered subset](https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-34717-agg-tut-cleanup/aggregation-tutorials/filtered-subset/)
- [group and total](https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-34717-agg-tut-cleanup/aggregation-tutorials/group-total/)
- [unpack arrays](https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-34717-agg-tut-cleanup/aggregation-tutorials/unpack-arrays/)
- [one to one](https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-34717-agg-tut-cleanup/aggregation-tutorials/one-to-one …
=> DOCSP-34717: agg tutorial cleanup + standardization

source/fundamentals/monitoring/cluster-monitoring.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-35296
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/node/DOCSP-35296-link-typos/fundamentals/monitoring/cluster-monitoring/#example-event-documents
=> DOCSP-35296 Fix swapped link text

source/compatibility.txt, source/fundamentals/connection.txt, source/fundamentals/connection/connect.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/index.txt, source/quick-reference.txt, source/quick-start.txt, source/usage-examples.txt, source/usage-examples/find.txt, source/usage-examples/findOne.txt, source/usage-examples/insertOne.txt
Hey @ccho-mongodb!  Would you please review this PR and merge it if everything looks good?  Please edit the descriptions to make them more accurate or descriptive as you see fit.  I mostly copied and pasted from text on the page; the description should be a short, general description of each page.
Thanks!
Sarah
JIRA - <https://jira.mongodb.org/browse/DOCSP-33172>
Staging - <https://preview-mongodbsarahemlin.gatsbyjs.io/node/DOCSP-33172/usage-examples/findOne/>
Build log - <https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655d1f8813dc9d16eadef880>
=> DOCSP-33172 added meta description for top 250 pages in docs-node

source/fundamentals/crud/read-operations/limit.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36060>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-36060-limit-typo-fix/fundamentals/crud/read-operations/limit/#limit
=> DOCSP-36060-fix-typo

source/fundamentals/aggregation.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36781>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/node/DOCSP-36781-agg-list-fix/fundamentals/aggregation/#references
=> DOCSP-36781: fix aggregation references list

source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/crud/write-operations/modify.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37187>
Staging
- [Retrieve](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-37187/fundamentals/crud/read-operations/retrieve/)
- [Modify](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-37187/fundamentals/crud/write-operations/modify/)
- [Insert](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-37187/fundamentals/crud/write-operations/insert/)
=> [Node] Build errors: Instruqt titles

source/aggregation-tutorials.txt, source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/crud/write-operations/modify.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37187>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/node/fix-build-errors/>
Build log - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65de287c7111165982cd7124
=> Fix 4.10 build errors

source/fundamentals/crud/read-operations/retrieve.txt, source/fundamentals/crud/write-operations/insert.txt, source/fundamentals/crud/write-operations/modify.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37187>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/node/DOCSP-37187-instruqt-fixes/>
Build log - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65de4ce37111165982e08a12
=> DOCSP-37187: Add Instruqt titles

source/faq.txt, source/fundamentals/collations.txt, source/fundamentals/crud/query-document.txt, source/fundamentals/crud/read-operations/distinct.txt, source/fundamentals/crud/read-operations/skip.txt, source/fundamentals/indexes.txt, source/usage-examples.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36899>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/node/DOCSP-36899-quarterly-tasks/>
=> DOCSP-36899: Quarterly cleanup

source/fundamentals/crud/write-operations/insert.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-37357>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/node/DOCSP-37357-insert-instruqt-updates/fundamentals/crud/write-operations/insert/>
=> DOCSP-37357: Update Insert Documents Instruqt rST

snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-36146
Staging - failed here for a reason i can't determine--maybe part of EOL?
=> DOCSP-36146 - EOL

source/index.txt, source/quick-start.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38547
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/node/DOCSP-38547-quickstart-title/quick-start/
=> DOCSP-38547 Standardize Quick Start Title

source/upgrade.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38947
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/node/DOCSP-38947-remove-broken-links/upgrade/#version-4.2-server-release-support-changes
=> DOCSP-38947 Remove broken links

source/fundamentals/connection/tls.txt
Modeled after similar messages in other driver docs ([example](https://www.mongodb.com/docs/drivers/csharp/current/fundamentals/connection/tls/))
JIRA - [DOCSP-34012](https://jira.mongodb.org/browse/DOCSP-34012)
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/node/DOCSP-34012-seedlist-note/fundamentals/connection/tls/>
=> DOCSP-34012: Further detail default TLS/SSL behavior when using DNS seedlist

source/fundamentals/gridfs.txt, source/includes/aggregation/filtered-subset.js, source/includes/aggregation/group-total.js, source/includes/aggregation/multi-field-join.js, source/includes/aggregation/one-to-one-join.js, source/includes/aggregation/unpack-arrays.js
JIRA: 
- https://jira.mongodb.org/browse/DOCSP-40183
- https://jira.mongodb.org/browse/DOCSP-40127
Staging:
- [GridFS](https://preview-mongodbmongokart.gatsbyjs.io/node/docsp-node-feedback/fundamentals/gridfs/)
- [Agg Tutorials](https://preview-mongodbmongokart.gatsbyjs.io/node/docsp-node-feedback/aggregation-tutorials/)
=> User Feedback

source/quick-start.txt, source/quick-start/connect-to-mongodb.txt, source/quick-start/create-a-connection-string.txt, source/quick-start/create-a-deployment.txt, source/quick-start/download-and-install.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41679>
Staging - <https://preview-mongodbstephmarie17.gatsbyjs.io/node/docsp-41679-removeNextStepsButtons/quick-start/>
=> DOCSP-41679 - Remove buttons from quick start

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-43976>
Staging - <https://deploy-preview-904--docs-node.netlify.app/>
=> DOCSP-43976 EOL v5.6

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-43976>
Staging - <https://deploy-preview-905--docs-node.netlify.app/>
=> DOCSP-43976 EOL v5.7

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-43976>
Staging - <https://deploy-preview-906--docs-node.netlify.app/>
=> DOCSP-43976 EOL v5.8

snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-43976>
Staging - <https://deploy-preview-907--docs-node.netlify.app/>
=> DOCSP-43976 EOL v5.9

source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44611>
Staging - <https://deploy-preview-921--docs-node.netlify.app/compatibility/>
=> DOCSP-44611: v6.10 sharedinclude tables

source/aggregation-tutorials.txt, source/fundamentals.txt, source/fundamentals/authentication.txt, source/fundamentals/bson.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/transactions.txt, source/usage-examples/update-and-replace-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44947>
Staging - <https://deploy-preview-923--docs-node.netlify.app/upgrade/>
=> DOCSP-44947 TOC Relabel

source/aggregation-tutorials.txt, source/fundamentals.txt, source/fundamentals/authentication.txt, source/fundamentals/bson.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/transactions.txt, source/usage-examples/update-and-replace-operations.txt
=> [Backport v6.10] DOCSP-44947 Shorten TOC

.github/workflows/backport.yml, source/aggregation-tutorials.txt, source/fundamentals.txt, source/fundamentals/authentication.txt, source/fundamentals/bson.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/transactions.txt, source/usage-examples/update-and-replace-operations.txt
=> [Backport v6.9] DOCSP-44947 Shorten TOC

.github/workflows/backport.yml, source/aggregation-tutorials.txt, source/fundamentals.txt, source/fundamentals/authentication.txt, source/fundamentals/bson.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/transactions.txt, source/usage-examples/update-and-replace-operations.txt
=> [Backport v6.8] DOCSP-44947 Shorten TOC 

.github/workflows/backport.yml, source/aggregation-tutorials.txt, source/fundamentals.txt, source/fundamentals/authentication.txt, source/fundamentals/bson.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/transactions.txt, source/usage-examples/update-and-replace-operations.txt
=> [Backport v6.7] DOCSP-44947 Shorten TOC 

source/aggregation-tutorials.txt, source/fundamentals.txt, source/fundamentals/authentication.txt, source/fundamentals/bson.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/transactions.txt, source/usage-examples/update-and-replace-operations.txt
=> [Backport v6.3] DOCSP-44947 TOC Relabel (#923)

source/aggregation-tutorials.txt, source/fundamentals.txt, source/fundamentals/authentication.txt, source/fundamentals/bson.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/transactions.txt, source/usage-examples/update-and-replace-operations.txt
=> [Backport v6.2] DOCSP-44947 TOC Relabel (#923)

source/aggregation-tutorials.txt, source/fundamentals.txt, source/fundamentals/authentication.txt, source/fundamentals/bson.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/transactions.txt, source/usage-examples/update-and-replace-operations.txt
=> [Backport v6.1] DOCSP-44947 TOC Relabel (#923)

source/aggregation-tutorials.txt, source/fundamentals.txt, source/fundamentals/authentication.txt, source/fundamentals/bson.txt, source/fundamentals/connection.txt, source/fundamentals/crud.txt, source/fundamentals/crud/read-operations.txt, source/fundamentals/crud/write-operations.txt, source/fundamentals/monitoring.txt, source/index.txt, source/quick-start.txt, source/usage-examples.txt, source/usage-examples/delete-operations.txt, source/usage-examples/find-operations.txt, source/usage-examples/insert-operations.txt, source/usage-examples/transactions.txt, source/usage-examples/update-and-replace-operations.txt
=> [Backport v6.0] DOCSP-44947 TOC Relabel (#923)

source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45694
Staging - https://deploy-preview-939--docs-node.netlify.app/whats-new/#std-label-version-6.11
=> DOCSP-45694 - fix OIDC wording

source/whats-new.txt
(cherry picked from commit d3cdc74f77e4b421eefc7b34cb7eb1712bcc1fa3)
=> typo fix (#939)

.github/workflows/vale-tdbx.yml, source/aggregation-tutorials/multi-field-join.txt
=> Fix vale check

source/fundamentals/authentication/mechanisms.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46472>
Staging - <https://deploy-preview-955--docs-node.netlify.app/fundamentals/authentication/mechanisms/>
I just deleted the link. The release notes for this version are no longer available. The note should be self explanatory without the reference.
=> [Node] Internal 404 - upgraded the authentication schema from MONGODB-CR to SCRAM

source/fundamentals/connection/connection-options.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-46766
Staging - https://deploy-preview-956--docs-node.netlify.app/fundamentals/connection/connection-options/ (second to last option)
=> DOCSP-46766 Add default to waitQueueTimeoutMS

source/fundamentals/indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46712>
Staging - <https://deploy-preview-959--docs-node.netlify.app/fundamentals/indexes/#list-indexes>
=> DOCSP-46712 ListIndexesOptions 404

source/fundamentals/connection/network-compression.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46711>
Staging - <https://deploy-preview-960--docs-node.netlify.app/fundamentals/connection/network-compression/#specify-compression-algorithms>
=> DOCSP-46711 MongoClientOptions 404

source/code-snippets/crud/cursor.js, source/fundamentals/crud/read-operations/cursor.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46884>
Staging - https://deploy-preview-979--docs-node.netlify.app/fundamentals/crud/read-operations/cursor/
=> DOCSP-46884 Abort signal support

.backportrc.json
JIRA - <https://jira.mongodb.org/browse/DOCSP-48088>
=> DOCSP-48088 change backporter script

source/code-snippets/indexes/text.js
JIRA - <https://jira.mongodb.org/browse/DOCSP-48736>
Staging - https://deploy-preview-1050--docs-node.netlify.app/fundamentals/indexes/#text-indexes
=> DOCSP-48736 - Fix createIndex() call

.github/pull_request_template.md, .github/workflows/add-netlify-links.yml
JIRA - <https://jira.mongodb.org/browse/DOCSP-48766>
=> DOCSP-48766 add netlify action

.github/pull_request_template.md
JIRA - <https://jira.mongodb.org/browse/DOCSP-48795>
No pages to preview
=> DOCSP-48795 Add PR checklist item for page titles

source/fundamentals/connection/csot.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49332>
<li><a href=https://deploy-preview-1087--docs-node.netlify.app/fundamentals/connection/csot>fundamentals/connection/csot</a></li>
=> DOCSP-49332 Fix hostname typo

config/redirects
=> Fix redirects for v6.15

source/index.txt
<li><a href=https://deploy-preview-1121--docs-node.netlify.app/index>index</a></li>
=> Fix broken refs on landing page

source/index.txt
=> [Backport v6.15] Fix broken refs on landing page

source/connect/connection-targets.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48760>
<li><a href=https://deploy-preview-1134--docs-node.netlify.app/connect/connection-targets>connect/connection-targets</a></li>
=> DOCSP-48760 Add replica set note

source/connect/connect.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48760>
[Connection Guide](https://deploy-preview-1136--docs-node.netlify.app/connect/connect/#connect-to-a-replica-set)
=> DOCSP-48760 Add replica set note for older versions

config/redirects
=> Fix redirects with version number

config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-50727
No pages to preview
=> DOCSP-50727 Add redirect for quick start landing page

source/aggregation/pipeline-stages.txt, source/index.txt, source/monitoring-and-logging/monitoring.txt
plus fixes some build errors
JIRA - <https://jira.mongodb.org/browse/DOCSP-52075>
<li><a href=https://deploy-preview-1203--docs-node.netlify.app/aggregation/pipeline-stages>aggregation/pipeline-stages</a></li><li><a href=https://deploy-preview-1203--docs-node.netlify.app/index>index</a></li><li><a href=https://deploy-preview-1203--docs-node.netlify.app/monitoring-and-logging/monitoring>monitoring-and-logging/monitoring</a></li>
=> DOCSP-52075 - Add databaseName property
